/** A custom-built, probably inefficient, emoji dataset and utility set */

const arrEmojis = [
    // People
    { emoji: '😀', name: 'grinning face smile happy' },
    { emoji: '😃', name: 'grinning face with big eyes happy smile excited' },
    { emoji: '😄', name: 'smile happy grin laughing' },
    { emoji: '😁', name: 'grinning face with smiling eyes happy smile pleased' },
    { emoji: '😆', name: 'grin squinting face laugh haha happy' },
    { emoji: '😅', name: 'nervous face with sweat awkward smile anxious' },
    { emoji: '🤣', name: 'rofl lmao lmfao rolling laughing floor funny' },
    { emoji: '😂', name: 'joy laugh lol tears crying happy' },
    { emoji: '🙂', name: 'slightly smiling face smile content' },
    { emoji: '🙃', name: 'upside down face silly playful ironic sarcastic' },
    { emoji: '😉', name: 'winking face wink flirt playful hint joke' },
    { emoji: '😊', name: 'smiling face with smiling eyes happy blush pleased' },
    { emoji: '😇', name: 'smiling face with halo angel innocent good' },
    { emoji: '🥰', name: 'smiling face with hearts love loving adore adorable' },
    { emoji: '😍', name: 'smiling face with heart eyes love crush infatuation adore' },
    { emoji: '🤩', name: 'star struck wow excited amazed impressed starstruck' },
    { emoji: '😘', name: 'face blowing a kiss kissing flirt love affection' },
    { emoji: '😗', name: 'kissing face kiss peck smooch' },
    { emoji: '😚', name: 'kissing face with closed eyes kiss affection' },
    { emoji: '😙', name: 'kissing face with smiling eyes kiss happy affection' },
    { emoji: '😋', name: 'face savoring food yum tasty delicious hungry' },
    { emoji: '😛', name: 'face with tongue silly playful teasing' },
    { emoji: '😜', name: 'winking face with tongue silly playful joke wink' },
    { emoji: '🤪', name: 'zany face crazy silly goofy wacky' },
    { emoji: '😝', name: 'squinting face with tongue silly playful joke' },
    { emoji: '🤑', name: 'money mouth face rich money wealthy dollar' },
    { emoji: '🤗', name: 'hugging face hug embrace cuddle arms open' },
    { emoji: '🤭', name: 'face with hand over mouth oops surprise shock secret' },
    { emoji: '🤫', name: 'shushing face quiet shh silence secret' },
    { emoji: '🤔', name: 'thinking face hmm wonder ponder thought' },
    { emoji: '🤐', name: 'zipper mouth face silent quiet zip secret' },
    { emoji: '🤨', name: 'face with raised eyebrow suspicious doubt skeptical' },
    { emoji: '😐', name: 'neutral face meh poker deadpan' },
    { emoji: '😑', name: 'expressionless face blank deadpan unimpressed' },
    { emoji: '😶', name: 'face without mouth silent quiet speechless' },
    { emoji: '😏', name: 'smirking face smug smirk flirt suggestive' },
    { emoji: '😒', name: 'unamused face unhappy unimpressed skeptical side eye' },
    { emoji: '🙄', name: 'face with rolling eyes eyeroll annoyed whatever' },
    { emoji: '😬', name: 'grimacing face awkward eek nervous' },
    { emoji: '🤥', name: 'lying face liar nose pinocchio fib' },
    { emoji: '😌', name: 'relieved face calm relaxed phew' },
    { emoji: '😔', name: 'pensive face sad reflective disappointed' },
    { emoji: '😪', name: 'sleepy face tired exhausted' },
    { emoji: '🤤', name: 'drooling face drool hungry desire want' },
    { emoji: '😴', name: 'sleeping face sleep zzz tired' },
    { emoji: '😷', name: 'face with medical mask sick ill virus covid pandemic' },
    { emoji: '🤒', name: 'face with thermometer sick fever ill unwell' },
    { emoji: '🤕', name: 'face with head bandage hurt injury wounded ouch' },
    { emoji: '🤢', name: 'nauseated face sick vomit green illness' },
    { emoji: '🤮', name: 'face vomiting sick throw up barf puke' },
    { emoji: '🤧', name: 'sneezing face achoo sick sneeze cold tissues' },
    { emoji: '🥵', name: 'hot face heat sweating overheated sun burning' },
    { emoji: '🥶', name: 'cold face freezing ice winter chill frozen' },
    { emoji: '🥴', name: 'woozy face dizzy drunk tipsy intoxicated' },
    { emoji: '😵', name: 'dizzy face confused disoriented shocked' },
    { emoji: '😵‍💫', name: 'face with spiral eyes dizzy confused disoriented' },
    { emoji: '🤯', name: 'exploding head shocked blown mind boom mindblown' },
    { emoji: '🤠', name: 'cowboy hat face western rodeo yeehaw' },
    { emoji: '🥳', name: 'partying face celebration party birthday festive' },
    { emoji: '😎', name: 'smiling face with sunglasses cool dude awesome chill rad' },
    { emoji: '🤓', name: 'nerd face geek glasses smart dork' },
    { emoji: '🧐', name: 'face with monocle sophisticated intelligent examine' },
    { emoji: '😕', name: 'confused face puzzled uncertain unsure' },
    { emoji: '😟', name: 'worried face concerned anxious nervous' },
    { emoji: '🙁', name: 'slightly frowning face sad upset disappointed' },
    { emoji: '☹️', name: 'frowning face sad upset disappointed unhappy' },
    { emoji: '😮', name: 'face with open mouth surprised shocked woah' },
    { emoji: '😯', name: 'hushed face surprised shocked stunned' },
    { emoji: '😲', name: 'astonished face shocked amazed surprised wow' },
    { emoji: '😳', name: 'flushed face embarrassed blushing shocked' },
    { emoji: '🥺', name: 'pleading face puppy eyes beg begging please' },
    { emoji: '😦', name: 'frowning face with open mouth shock horror surprise' },
    { emoji: '😧', name: 'anguished face shocked horrified concerned' },
    { emoji: '😨', name: 'fearful face scared terrified afraid shock' },
    { emoji: '😰', name: 'anxious face with sweat nervous worried stressed' },
    { emoji: '😥', name: 'sad but relieved face disappointed disappointed but relieved' },
    { emoji: '😢', name: 'crying face sad tear tears upset' },
    { emoji: '😭', name: 'loudly crying face sobbing wailing bawling tears' },
    { emoji: '😱', name: 'face screaming in fear scream horror terrified' },
    { emoji: '😖', name: 'confounded face confused frustrated upset' },
    { emoji: '😣', name: 'persevering face struggling determined persisting' },
    { emoji: '😞', name: 'disappointed face sad disappointed upset' },
    { emoji: '😓', name: 'downcast face with sweat stressed sad disappointed' },
    { emoji: '😩', name: 'weary face tired exhausted frustrated' },
    { emoji: '😫', name: 'tired face exhausted frustrated annoyed' },
    { emoji: '🥱', name: 'yawning face sleepy tired bored' },
    { emoji: '😤', name: 'face with steam from nose angry mad frustrated hmph' },
    { emoji: '😡', name: 'pouting face angry mad rage furious' },
    { emoji: '😠', name: 'angry face mad annoyed frustrated' },
    { emoji: '🤬', name: 'face with symbols on mouth cursing swearing cussing' },
    { emoji: '🤒', name: 'face with thermometer sick ill unwell fever' },
    { emoji: '🤕', name: 'face with head bandage injured hurt wounded ouch' },
    { emoji: '😈', name: 'smiling face with horns devil evil mischievous naughty' },
    { emoji: '👿', name: 'angry face with horns devil demon evil mad' },
    { emoji: '💀', name: 'skull death dead danger poison' },
    { emoji: '☠️', name: 'skull and crossbones poison danger pirate death' },
    { emoji: '💩', name: 'pile of poo poop dung crap shit' },
    { emoji: '🤡', name: 'clown face circus funny joke' },
    { emoji: '👹', name: 'ogre monster creature ugly scary' },
    { emoji: '👺', name: 'goblin creature scary ugly monster' },
    { emoji: '👻', name: 'ghost spooky scary halloween boo' },
    { emoji: '👽', name: 'alien ufo et extraterrestrial space' },
    { emoji: '👾', name: 'alien monster space invader game retro' },
    { emoji: '🤖', name: 'robot mechanical bot automation' },

    // Gestures & Body Parts
    { emoji: '👋', name: 'waving hand hello goodbye wave hi bye' },
    { emoji: '🤚', name: 'raised back of hand highfive stop halt' },
    { emoji: '🖐️', name: 'hand with fingers splayed stop halt' },
    { emoji: '✋', name: 'raised hand highfive stop halt' },
    { emoji: '🖖', name: 'vulcan salute spock star trek prosper' },
    { emoji: '👌', name: 'ok hand okay perfect nice good' },
    { emoji: '🤏', name: 'pinching hand small tiny little bit' },
    { emoji: '✌️', name: 'victory hand peace v sign yeah' },
    { emoji: '🤞', name: 'crossed fingers luck hopeful wishing' },
    { emoji: '🤟', name: 'love you gesture ily rock music sign' },
    { emoji: '🤘', name: 'rock on sign metal music concert' },
    { emoji: '👇', name: 'backhand index pointing down finger point below' },
    { emoji: '👆', name: 'backhand index pointing up finger point above' },
    { emoji: '👉', name: 'backhand index pointing right finger point this way' },
    { emoji: '👈', name: 'backhand index pointing left finger point that way' },
    { emoji: '👍', name: 'thumbs up like approve good positive' },
    { emoji: '👎', name: 'thumbs down dislike disapprove bad negative' },
    { emoji: '✊', name: 'raised fist power solidarity strength' },
    { emoji: '👊', name: 'oncoming fist punch bro fist bump' },
    { emoji: '🤛', name: 'left facing fist bump pound' },
    { emoji: '🤜', name: 'right facing fist bump pound' },
    { emoji: '👏', name: 'clapping hands applause praise congrats' },
    { emoji: '🙌', name: 'raising hands celebration hooray praise' },
    { emoji: '👐', name: 'open hands welcome jazz hands' },
    { emoji: '🤲', name: 'palms up together pray please beg offering' },
    { emoji: '🤝', name: 'handshake deal agreement meeting greet' },
    { emoji: '🙏', name: 'folded hands please thank you pray prayer namaste' },
    { emoji: '💪', name: 'flexed biceps strong strength muscle flex power' },
    { emoji: '🦾', name: 'mechanical arm robot prosthetic bionic' },
    { emoji: '🦿', name: 'mechanical leg robot prosthetic bionic' },
    { emoji: '🦵', name: 'leg kick foot limb' },
    { emoji: '🦶', name: 'foot toe sole kick' },
    { emoji: '👂', name: 'ear hearing listen sound' },
    { emoji: '🦻', name: 'ear with hearing aid deaf accessible' },
    { emoji: '👃', name: 'nose smell scent sniff' },
    { emoji: '🧠', name: 'brain mind intellectual smart intelligence' },
    { emoji: '👀', name: 'eyes see look watch view peek' },
    { emoji: '👅', name: 'tongue taste lick flavor' },
    { emoji: '👄', name: 'mouth lips kiss speaking' },
    { emoji: '🫀', name: 'anatomical heart organ cardiac love' },
    { emoji: '🫁', name: 'lungs breathing organ respiratory' },
    { emoji: '🦷', name: 'tooth dental dentist molar teeth' },
    { emoji: '🦴', name: 'bone skeleton structure' },
    { emoji: '👁️', name: 'eye see view vision sight' },
    { emoji: '🖕', name: 'middle finger fuck you rude offensive' },
    { emoji: '💅', name: 'nail polish manicure self care beauty' },

    // Food
    { emoji: '🍏', name: 'green apple fruit healthy food' },
    { emoji: '🍎', name: 'red apple fruit healthy food' },
    { emoji: '🍐', name: 'pear fruit healthy food' },
    { emoji: '🍊', name: 'tangerine orange fruit citrus' },
    { emoji: '🍋', name: 'lemon fruit citrus sour' },
    { emoji: '🍌', name: 'banana fruit food potassium' },
    { emoji: '🍉', name: 'watermelon fruit summer food' },
    { emoji: '🍇', name: 'grapes fruit food wine' },
    { emoji: '🍓', name: 'strawberry fruit red berry' },
    { emoji: '🍈', name: 'melon fruit food honeydew cantaloupe' },
    { emoji: '🍒', name: 'cherries fruit red food berry' },
    { emoji: '🍑', name: 'peach fruit food butt ass booty' },
    { emoji: '🥭', name: 'mango fruit tropical food' },
    { emoji: '🍍', name: 'pineapple fruit tropical food' },
    { emoji: '🥥', name: 'coconut fruit tropical food' },
    { emoji: '🥝', name: 'kiwi fruit food green' },
    { emoji: '🍅', name: 'tomato vegetable fruit food' },
    { emoji: '🥑', name: 'avocado fruit food guacamole' },
    { emoji: '🍆', name: 'eggplant vegetable food aubergine dick penis cock' },
    { emoji: '🥔', name: 'potato vegetable food tuber' },
    { emoji: '🥕', name: 'carrot vegetable food orange' },
    { emoji: '🌽', name: 'ear of corn vegetable food maize' },
    { emoji: '🌶️', name: 'hot pepper vegetable food spicy chili' },
    { emoji: '🥒', name: 'cucumber vegetable food pickle' },
    { emoji: '🥬', name: 'leafy green vegetable food lettuce kale spinach' },
    { emoji: '🥦', name: 'broccoli vegetable food green' },
    { emoji: '🧄', name: 'garlic vegetable food spice' },
    { emoji: '🧅', name: 'onion vegetable food spice' },
    { emoji: '🍄', name: 'mushroom fungi food toadstool' },
    { emoji: '🥜', name: 'peanuts food nuts legume' },
    { emoji: '🌰', name: 'chestnut food nut' },
    { emoji: '🍞', name: 'bread food loaf bakery' },
    { emoji: '🥐', name: 'croissant food bread bakery french' },
    { emoji: '🥖', name: 'baguette bread food french bakery' },
    { emoji: '🥨', name: 'pretzel food bread twisted' },
    { emoji: '🥯', name: 'bagel food bread bakery breakfast' },
    { emoji: '🥞', name: 'pancakes food breakfast hotcakes' },
    { emoji: '🧇', name: 'waffle food breakfast dessert' },
    { emoji: '🧀', name: 'cheese wedge food dairy' },
    { emoji: '🍳', name: 'cooking egg breakfast food frying pan' },
    { emoji: '🍲', name: 'pot of food stew soup meal dinner' },
    { emoji: '🥣', name: 'bowl with spoon food cereal soup breakfast' },
    { emoji: '🥗', name: 'green salad food healthy lettuce vegetable' },
    { emoji: '🍿', name: 'popcorn food snack movie cinema' },
    { emoji: '🧈', name: 'butter food dairy ingredient' },
    { emoji: '🍗', name: 'poultry leg food meat chicken turkey' },
    { emoji: '🍖', name: 'meat on bone food meat rib' },
    { emoji: '🥩', name: 'cut of meat food steak beef' },
    { emoji: '🍔', name: 'hamburger food burger fast food beef' },
    { emoji: '🍟', name: 'french fries food potato chips fast food' },
    { emoji: '🌭', name: 'hot dog food sausage fast food' },
    { emoji: '🍕', name: 'pizza food cheese pepperoni italian' },
    { emoji: '🌮', name: 'taco food mexican tortilla' },
    { emoji: '🌯', name: 'burrito food mexican wrap' },
    { emoji: '🥙', name: 'stuffed flatbread food gyro kebab' },
    { emoji: '🍤', name: 'fried shrimp food seafood tempura' },
    { emoji: '🍚', name: 'cooked rice food asian' },
    { emoji: '🍛', name: 'curry rice food spicy asian' },
    { emoji: '🍜', name: 'steaming bowl noodles ramen soup food' },
    { emoji: '🍝', name: 'spaghetti food pasta noodles italian' },
    { emoji: '🍠', name: 'roasted sweet potato food vegetable' },
    { emoji: '🍢', name: 'oden food stick skewer asian' },
    { emoji: '🍣', name: 'sushi food fish japanese rice' },
    { emoji: '🍱', name: 'bento box food japanese' },
    { emoji: '🥟', name: 'dumpling food asian chinese potsticker' },
    { emoji: '🍘', name: 'rice cracker food japanese snack' },
    { emoji: '🍙', name: 'rice ball food japanese onigiri' },
    { emoji: '🍡', name: 'dango food dessert sweet japanese' },
    { emoji: '🥮', name: 'moon cake food dessert festival chinese' },
    { emoji: '🍧', name: 'shaved ice dessert sweet cold' },
    { emoji: '🍨', name: 'ice cream food dessert sweet cold' },
    { emoji: '🍦', name: 'soft ice cream food dessert sweet cold cone' },
    { emoji: '🥧', name: 'pie food dessert pastry sweet' },
    { emoji: '🍰', name: 'shortcake food dessert sweet cake slice birthday' },
    { emoji: '🎂', name: 'birthday cake food dessert sweet celebration' },
    { emoji: '🍮', name: 'custard food dessert sweet pudding flan' },
    { emoji: '🍭', name: 'lollipop candy sweet dessert food' },
    { emoji: '🍬', name: 'candy sweet dessert food sucker' },
    { emoji: '🍫', name: 'chocolate bar food sweet dessert snack' },
    { emoji: '🍩', name: 'doughnut food sweet dessert donut breakfast' },
    { emoji: '🍪', name: 'cookie food sweet dessert snack chocolate' },
    { emoji: '☕', name: 'hot beverage coffee tea drink caffeine' },
    { emoji: '🍵', name: 'teacup without handle tea drink hot green asian' },
    { emoji: '🥛', name: 'glass of milk food dairy breakfast drink' },
    { emoji: '🍼', name: 'baby bottle milk food drink infant formula' },
    { emoji: '🍺', name: 'beer mug alcohol drink beverage pub' },
    { emoji: '🍻', name: 'clinking beer mugs drink alcohol cheers toast' },
    { emoji: '🥂', name: 'clinking glasses drink champagne toast celebration' },
    { emoji: '🍷', name: 'wine glass alcohol drink beverage' },
    { emoji: '🥃', name: 'tumbler glass whiskey alcohol scotch drink' },
    { emoji: '🍸', name: 'cocktail glass drink alcohol martini' },
    { emoji: '🍹', name: 'tropical drink cocktail alcohol beach' },
    { emoji: '🍾', name: 'bottle with popping cork champagne wine celebration' },
    { emoji: '🥤', name: 'cup with straw drink soda beverage' },
    { emoji: '🧃', name: 'beverage box drink juice' },
    { emoji: '🧉', name: 'mate drink tea beverage herb' },
    { emoji: '🧊', name: 'ice cube cold freeze winter' },
    { emoji: '🥢', name: 'chopsticks utensil asian chinese japanese' },
    { emoji: '🍽️', name: 'fork and knife with plate dining utensil food' },
    { emoji: '🍴', name: 'fork and knife utensil food silverware' },
    { emoji: '🥄', name: 'spoon utensil silverware food' },
    { emoji: '🔪', name: 'kitchen knife cook food weapon utensil chef' },
    { emoji: '🍶', name: 'sake bottle and cup alcohol drink japanese' },
    { emoji: '🥫', name: 'canned food soup tin preserved' },
    { emoji: '🫐', name: 'blueberries fruit berries food healthy' },
    { emoji: '🫑', name: 'bell pepper vegetable food' },
    { emoji: '🫓', name: 'flatbread food pita naan' },
    { emoji: '🫔', name: 'tamale food mexican wrap' },
    { emoji: '🫕', name: 'fondue food melted cheese pot' },
    { emoji: '🧋', name: 'bubble tea drink boba milk tea' },
    { emoji: '🧆', name: 'falafel food mediterranean chickpea' },
    { emoji: '🥠', name: 'fortune cookie food dessert prophecy chinese' },
    { emoji: '🥡', name: 'takeout box food leftover chinese' },
    { emoji: '🫘', name: 'beans food legumes protein' },
    { emoji: '🫗', name: 'pouring liquid water drink pouring beverage' },

    // Animals
    { emoji: '🐨', name: 'koala animal australia marsupial' },
    { emoji: '🦥', name: 'sloth animal slow lazy sleepy' },
    { emoji: '🦦', name: 'otter animal water river sea' },
    { emoji: '🦨', name: 'skunk animal smelly stinky' },
    { emoji: '🦩', name: 'flamingo bird pink tropical zoo' },
    { emoji: '🐦', name: 'bird animal flying pet avian chirp sing' },
    { emoji: '🦜', name: 'parrot bird tropical colorful pet' },
    { emoji: '🦢', name: 'swan bird elegant water grace' },
    { emoji: '🦅', name: 'eagle bird predator raptor hunting' },
    { emoji: '🐧', name: 'penguin bird arctic antarctic cold' },
    { emoji: '🕊️', name: 'dove bird peace white fly' },
    { emoji: '🦉', name: 'owl bird night wise nocturnal hoot' },
    { emoji: '🦚', name: 'peacock bird colorful feathers' },
    { emoji: '🦤', name: 'dodo bird extinct' },
    { emoji: '🦠', name: 'microbe bacteria virus germ cell' },
    { emoji: '🐤', name: 'baby chick bird yellow young hatch' },
    { emoji: '🐥', name: 'front facing baby chick bird yellow young' },
    { emoji: '🐣', name: 'hatching chick bird egg hatching baby' },
    { emoji: '🐺', name: 'wolf face animal wild dog howl' },
    { emoji: '🦝', name: 'raccoon animal masked bandit' },
    { emoji: '🐗', name: 'boar animal wild pig forest' },
    { emoji: '🐴', name: 'horse face animal equestrian' },
    { emoji: '🦄', name: 'unicorn face animal fantasy magic mythical' },
    { emoji: '🦓', name: 'zebra animal stripes safari wildlife' },
    { emoji: '🦒', name: 'giraffe animal tall spots savanna' },
    { emoji: '🐪', name: 'camel animal desert hump' },
    { emoji: '🐫', name: 'two hump camel animal desert bactrian' },
    { emoji: '🦙', name: 'llama animal alpaca wool' },
    { emoji: '🦘', name: 'kangaroo animal australia marsupial jump' },
    { emoji: '🐂', name: 'ox animal bull cow farm' },
    { emoji: '🐃', name: 'water buffalo animal ox cow' },
    { emoji: '🐄', name: 'cow animal bovine farm milk' },
    { emoji: '🐑', name: 'sheep animal wool farm baa' },
    { emoji: '🐐', name: 'goat animal farm' },
    { emoji: '🐏', name: 'ram animal sheep male' },
    { emoji: '🐖', name: 'pig animal farm oink hog' },
    { emoji: '🐕', name: 'dog animal pet puppy canine' },
    { emoji: '🐩', name: 'poodle dog animal pet canine' },
    { emoji: '🐈', name: 'cat animal pet kitten feline' },
    { emoji: '🐱', name: 'cat face animal pet kitten feline meow' },
    { emoji: '🦇', name: 'bat animal nocturnal flying' },
    { emoji: '🐀', name: 'rat animal rodent mouse' },
    { emoji: '🐁', name: 'mouse animal rodent rat' },
    { emoji: '🦔', name: 'hedgehog animal spiny prickly' },
    { emoji: '🦡', name: 'badger animal forest' },
    { emoji: '🐿️', name: 'chipmunk animal squirrel rodent' },
    { emoji: '🐾', name: 'paw prints animal track footprints' },
    { emoji: '🦀', name: 'crab animal shellfish sea ocean' },
    { emoji: '🦞', name: 'lobster animal shellfish seafood' },
    { emoji: '🦐', name: 'shrimp animal shellfish seafood' },
    { emoji: '🦑', name: 'squid animal ocean sea tentacles' },
    { emoji: '🐙', name: 'octopus animal sea ocean tentacles' },
    { emoji: '🦪', name: 'oyster animal shellfish pearl sea' },
    { emoji: '🐠', name: 'tropical fish animal aquarium' },
    { emoji: '🐟', name: 'fish animal sea ocean aquarium' },
    { emoji: '🐡', name: 'blowfish animal sea ocean pufferfish' },
    { emoji: '🐬', name: 'dolphin animal sea ocean marine' },
    { emoji: '🐳', name: 'spouting whale animal sea ocean marine' },
    { emoji: '🐋', name: 'whale animal sea ocean marine' },
    { emoji: '🦈', name: 'shark animal sea ocean predator' },
    { emoji: '🐊', name: 'crocodile animal reptile alligator' },
    { emoji: '🐢', name: 'turtle animal reptile tortoise slow' },
    { emoji: '🦎', name: 'lizard animal reptile' },
    { emoji: '🐍', name: 'snake animal reptile serpent python' },
    { emoji: '🐉', name: 'dragon animal mythical fantasy' },
    { emoji: '🦕', name: 'sauropod dinosaur extinct brontosaurus' },
    { emoji: '🦖', name: 'T Rex dinosaur extinct tyrannosaurus' },
    { emoji: '🐲', name: 'dragon face animal mythical fantasy' },
    { emoji: '🦂', name: 'scorpion animal arachnid sting' },
    { emoji: '🕷️', name: 'spider animal arachnid insect bug' },
    { emoji: '🕸️', name: 'spider web spiderweb cobweb' },
    { emoji: '🐜', name: 'ant insect bug tiny pest' },
    { emoji: '🐝', name: 'honeybee insect bee honey buzz' },
    { emoji: '🐞', name: 'lady beetle insect bug ladybug ladybird' },
    { emoji: '🦗', name: 'cricket insect grasshopper bug' },
    { emoji: '🪳', name: 'cockroach insect bug pest' },
    { emoji: '🐌', name: 'snail animal slow shell' },
    { emoji: '🦋', name: 'butterfly insect bug pretty beautiful' },
    { emoji: '🐛', name: 'bug insect worm caterpillar' },
    { emoji: '🐌', name: 'snail slow shell animal' },
    { emoji: '🦟', name: 'mosquito insect bug pest malaria' },
    { emoji: '🦮', name: 'guide dog service animal blind seeing eye' },
    { emoji: '🐕‍🦺', name: 'service dog assistance animal support' },
    { emoji: '🐩', name: 'poodle dog pet animal' },
    { emoji: '🐈‍⬛', name: 'black cat feline animal pet' },
    { emoji: '🦬', name: 'bison animal buffalo ox' },
    { emoji: '🦣', name: 'mammoth extinct animal elephant prehistoric' },
    { emoji: '🦫', name: 'beaver animal dam rodent' },
    { emoji: '🐻', name: 'bear animal forest wild' },
    { emoji: '🐻‍❄️', name: 'polar bear arctic white cold animal' },
    { emoji: '🐼', name: 'panda animal bamboo china' },
    { emoji: '🦁', name: 'lion animal wild cat jungle king' },
    { emoji: '🐯', name: 'tiger face animal wild cat jungle' },
    { emoji: '🐅', name: 'tiger animal wild cat jungle' },
    { emoji: '🐆', name: 'leopard animal wild cat spots' },
    { emoji: '🐎', name: 'horse animal race equestrian' },
    { emoji: '🦧', name: 'orangutan animal primate monkey ape' },
    { emoji: '🦍', name: 'gorilla animal ape monkey' },
    { emoji: '🦧', name: 'orangutan ape primate monkey animal' },
    { emoji: '🐘', name: 'elephant animal big tusks trunk' },
    { emoji: '🦏', name: 'rhinoceros animal rhino horn' },
    { emoji: '🦛', name: 'hippopotamus animal hippo water' },
    { emoji: '🦓', name: 'zebra animal stripes' },
    { emoji: '🦬', name: 'bison animal buffalo ox' },
    { emoji: '🦙', name: 'llama animal alpaca wool' },
    { emoji: '🦌', name: 'deer animal bambi antlers' },
    { emoji: '🐶', name: 'dog face animal pet canine puppy' },
    { emoji: '🐰', name: 'rabbit face animal bunny pet' },
    { emoji: '🐹', name: 'hamster face animal pet rodent' },
    { emoji: '🦊', name: 'fox face animal cunning' },
    { emoji: '🐭', name: 'mouse face animal rodent pet' },
    { emoji: '🐹', name: 'hamster face animal pet rodent' },
    { emoji: '🐻', name: 'bear face animal wild forest' },
    { emoji: '🐼', name: 'panda face animal bear bamboo china' },
    { emoji: '🐨', name: 'koala face animal australian marsupial' },
    { emoji: '🐯', name: 'tiger face animal wild cat jungle' },
    { emoji: '🦁', name: 'lion face animal wild cat king' },
    { emoji: '🐮', name: 'cow face animal farm' },
    { emoji: '🐷', name: 'pig face animal oink farm' },
    { emoji: '🐸', name: 'frog face animal toad amphibian' },
    { emoji: '🐵', name: 'monkey face animal primate ape' },
    { emoji: '🙈', name: 'see no evil monkey animal primate hides eyes' },
    { emoji: '🙉', name: 'hear no evil monkey animal primate covers ears' },
    { emoji: '🙊', name: 'speak no evil monkey animal primate covers mouth' },
    
    // Items
    { emoji: '🎒', name: 'backpack bag school travel hiking' },
    { emoji: '👓', name: 'glasses eyeglasses spectacles eyewear' },
    { emoji: '🕶️', name: 'sunglasses shades cool eyewear' },
    { emoji: '🌂', name: 'closed umbrella rain weather protection' },
    { emoji: '🧳', name: 'luggage suitcase travel bag baggage' },
    { emoji: '👜', name: 'handbag purse bag fashion accessory' },
    { emoji: '👛', name: 'purse wallet money bag fashion' },
    { emoji: '👝', name: 'pouch bag small container clutch' },
    { emoji: '🎽', name: 'running shirt athletics sportswear' },
    { emoji: '👕', name: 't shirt clothing top shirt casual' },
    { emoji: '👖', name: 'jeans pants denim trousers clothing' },
    { emoji: '🧣', name: 'scarf neckwear winter accessory' },
    { emoji: '🧤', name: 'gloves mittens winter handwear' },
    { emoji: '🧥', name: 'coat jacket winter clothing outerwear' },
    { emoji: '🧦', name: 'socks feet clothing footwear' },
    { emoji: '👗', name: 'dress clothing outfit fashion women' },
    { emoji: '👙', name: 'bikini swimwear swimsuit beach' },
    { emoji: '👘', name: 'kimono dress clothing traditional japanese' },
    { emoji: '👠', name: 'high heeled shoe pumps fashion women' },
    { emoji: '👡', name: 'sandal shoe footwear summer' },
    { emoji: '👢', name: 'boot shoe footwear winter' },
    { emoji: '👞', name: 'shoe formal leather footwear' },
    { emoji: '👟', name: 'running shoe sneakers trainers athletic' },
    { emoji: '👒', name: 'hat fashion summer accessory' },
    { emoji: '🎩', name: 'top hat formal magic fancy' },
    { emoji: '🎓', name: 'graduation cap academic degree university school' },
    { emoji: '🧢', name: 'billed cap baseball hat snapback' },
    { emoji: '⛑️', name: 'rescue worker helmet safety protection' },
    { emoji: '💼', name: 'briefcase business work office bag' },
    { emoji: '📱', name: 'mobile phone smartphone iphone android cell' },
    { emoji: '📲', name: 'mobile phone with arrow call incoming' },
    { emoji: '☎️', name: 'telephone landline call phone' },
    { emoji: '📞', name: 'telephone receiver handset call phone' },
    { emoji: '📟', name: 'pager beeper old tech device' },
    { emoji: '📠', name: 'fax machine office old tech device' },
    { emoji: '🔋', name: 'battery power energy charge electricity' },
    { emoji: '🔌', name: 'electric plug power outlet electricity' },
    { emoji: '💡', name: 'light bulb idea electricity lamp' },
    { emoji: '🔦', name: 'flashlight torch light portable' },
    { emoji: '🕯️', name: 'candle light wax flame' },
    { emoji: '🪔', name: 'diya lamp light oil hindu diwali' },
    { emoji: '💣', name: 'bomb explosive boom danger weapon' },
    { emoji: '🧨', name: 'firecracker explosive firework celebration' },
    { emoji: '🔫', name: 'pistol gun weapon water toy' },
    { emoji: '🧰', name: 'toolbox tools repair fix maintenance' },
    { emoji: '🪛', name: 'screwdriver tool repair fix' },
    { emoji: '🔧', name: 'wrench tool repair fix mechanical' },
    { emoji: '🔨', name: 'hammer tool construction repair' },
    { emoji: '⛏️', name: 'pick tool mining construction' },
    { emoji: '🪓', name: 'axe tool weapon wood lumberjack' },
    { emoji: '🔩', name: 'nut and bolt hardware tool fastener' },
    { emoji: '⚙️', name: 'gear cog mechanical settings' },
    { emoji: '🧱', name: 'brick building construction wall' },
    { emoji: '🪝', name: 'hook tool catch fishing hang' },
    { emoji: '🧲', name: 'magnet attraction metal magnetic' },
    { emoji: '🔗', name: 'link chain connection url attach' },
    { emoji: '🧷', name: 'safety pin fastener diaper clasp' },
    { emoji: '🧴', name: 'lotion bottle moisturizer sunscreen cosmetic' },
    { emoji: '🧵', name: 'thread spool sewing string craft' },
    { emoji: '🧶', name: 'yarn ball knitting craft crochet' },
    { emoji: '🪡', name: 'sewing needle thread craft stitch' },
    { emoji: '📌', name: 'pushpin pin tack office' },
    { emoji: '📍', name: 'round pushpin pin location map tack' },
    { emoji: '📎', name: 'paperclip office supplies attachment' },
    { emoji: '🖇️', name: 'linked paperclips office supplies attachment' },
    { emoji: '✂️', name: 'scissors cut tool craft office' },
    { emoji: '🧹', name: 'broom sweep clean housework' },
    { emoji: '🧺', name: 'basket container laundry picnic wicker' },
    { emoji: '🧼', name: 'soap bar wash hygiene clean' },
    { emoji: '🪠', name: 'plunger toilet unclog plumbing' },
    { emoji: '🪣', name: 'bucket pail container water cleaning' },
    { emoji: '🧽', name: 'sponge cleaning absorbent wash' },
    { emoji: '🪤', name: 'mouse trap rodent pest catch' },
    { emoji: '💊', name: 'pill medicine drug health pharmacy' },
    { emoji: '💉', name: 'syringe injection vaccine medicine needle' },
    { emoji: '📄', name: 'page document paper file' },
    { emoji: '📃', name: 'page with curl document paper file' },
    { emoji: '📑', name: 'bookmark tabs markers colors organize' },
    { emoji: '📊', name: 'bar chart graph statistics presentation' },
    { emoji: '📈', name: 'chart increasing graph up trending stats' },
    { emoji: '📉', name: 'chart decreasing graph down trending stats' },
    { emoji: '📇', name: 'card index organizer contacts rolodex' },
    { emoji: '🗃️', name: 'card file box storage organize office' },
    { emoji: '🗄️', name: 'file cabinet storage organize office' },
    { emoji: '🗑️', name: 'wastebasket trash garbage bin delete' },
    { emoji: '🔒', name: 'locked security protection private' },
    { emoji: '🔓', name: 'unlocked open security access' },
    { emoji: '🔏', name: 'locked with pen secure private writing' },
    { emoji: '🔐', name: 'locked with key secure private' },
    { emoji: '🔑', name: 'key unlock password security access' },
    { emoji: '🗝️', name: 'old key antique vintage security' },
    { emoji: '🪑', name: 'chair seat furniture' },
    { emoji: '🛋️', name: 'couch and lamp sofa furniture relax' },
    { emoji: '🛌', name: 'person in bed sleep rest hotel' },
    { emoji: '🛏️', name: 'bed furniture sleep rest' },
    { emoji: '🚪', name: 'door entrance exit entry' },
    { emoji: '🪟', name: 'window view building opening' },

    // Hearts
    { emoji: '❤️', name: 'red heart love romance like affection' },
    { emoji: '🧡', name: 'orange heart love like affection' },
    { emoji: '💛', name: 'yellow heart love like affection' },
    { emoji: '💚', name: 'green heart love like affection' },
    { emoji: '💙', name: 'blue heart love like affection' },
    { emoji: '💜', name: 'purple heart love like affection' },
    { emoji: '🤎', name: 'brown heart love like affection' },
    { emoji: '🖤', name: 'black heart love emo goth dark' },
    { emoji: '🤍', name: 'white heart love pure clean' },
    { emoji: '💕', name: 'two hearts love couple relationship romance' },
    { emoji: '💞', name: 'revolving hearts love relationship animated' },
    { emoji: '💓', name: 'beating heart love heartbeat pulse' },
    { emoji: '💗', name: 'growing heart love increase excited' },
    { emoji: '💖', name: 'sparkling heart love excitement sparkle' },
    { emoji: '💘', name: 'heart with arrow love cupid struck' },
    { emoji: '💝', name: 'heart with ribbon love gift valentine' },
    { emoji: '💟', name: 'heart decoration love ornament' },
    { emoji: '❣️', name: 'heart exclamation love emphasis punctuation' },
    { emoji: '💔', name: 'broken heart sad heartbreak breakup' },
    { emoji: '❤️‍🔥', name: 'heart on fire love passion intense' },
    { emoji: '❤️‍🩹', name: 'mending heart love healing recovery' },

    // Symbols
    { emoji: '✨', name: 'sparkles glitter shiny stars magic' },
    { emoji: '🌟', name: 'glowing star shiny sparkle glitter bright' },
    { emoji: '⭐', name: 'star rating favorite bookmark yellow' },
    { emoji: '💫', name: 'dizzy star sparkle spin swirl' },
    { emoji: '🔥', name: 'fire flame hot burn lit trending' },
    { emoji: '☄️', name: 'comet space asteroid shooting star' },
    { emoji: '💥', name: 'collision boom bang explosion crash' },
    { emoji: '💢', name: 'anger mad symbol angry irritated rage' },
    { emoji: '💬', name: 'speech balloon message talk chat balloon' },
    { emoji: '👁️‍🗨️', name: 'eye in speech bubble witness statement' },
    { emoji: '🗯️', name: 'right anger bubble rage mad angry' },
    { emoji: '💭', name: 'thought balloon think dream wonder imagine' },
    { emoji: '🗨️', name: 'left speech bubble talk chat message' },
    { emoji: '🔯', name: 'dotted six pointed star jewish star of david' },
    { emoji: '✡️', name: 'star of david jewish religion hebrew' },
    { emoji: '✝️', name: 'latin cross christian religion christianity' },
    { emoji: '☪️', name: 'star and crescent islam muslim religion' },
    { emoji: '🕉️', name: 'om hindu religion spiritual' },
    { emoji: '☸️', name: 'wheel of dharma buddhist buddhism religion' },
    { emoji: '☮️', name: 'peace symbol harmony pacifism' },
    { emoji: '🔄', name: 'counterclockwise arrows button reload refresh' },
    { emoji: '🔃', name: 'clockwise vertical arrows reload sync' },
    { emoji: '🈂️', name: 'japanese "service charge" button kanji' },
    { emoji: '🈁', name: 'japanese "here" button kanji' },
    { emoji: '🈹', name: 'japanese "discount" button kanji' },
    { emoji: '🈶', name: 'japanese "not free of charge" button kanji' },
    { emoji: '🈯', name: 'japanese "reserved" button kanji' },
    { emoji: '🉐', name: 'japanese "bargain" button kanji' },
    { emoji: '💯', name: 'hundred points perfect score 100 percent' },
    { emoji: '🔠', name: 'input latin uppercase letters ABC uppercase' },
    { emoji: '🔡', name: 'input latin lowercase letters abc lowercase' },
    { emoji: '🔢', name: 'input numbers 123 number digits' },
    { emoji: '🔣', name: 'input symbols special characters' },
    { emoji: '🔤', name: 'input latin letters abc alphabet' },
    { emoji: '🆎', name: 'AB button blood type' },
    { emoji: '🆑', name: 'CL button clear delete' },
    { emoji: '🆒', name: 'COOL button word cool' },
    { emoji: '🆓', name: 'FREE button free no charge' },
    { emoji: '🆔', name: 'ID button identification identity' },
    { emoji: '🆕', name: 'NEW button new item badge' },
    { emoji: '🆖', name: 'NG button not good no good' },
    { emoji: '🆗', name: 'OK button okay good agree' },
    { emoji: '🆘', name: 'SOS button emergency help sos' },
    { emoji: '🆙', name: 'UP! button up level increase' },
    { emoji: '🆚', name: 'VS button versus competition against' },
    { emoji: '🈁', name: 'Japanese "here" button kanji' },
    { emoji: '🈂️', name: 'Japanese "service charge" button kanji' },
    { emoji: '🈷️', name: 'Japanese "monthly amount" button kanji' },
    { emoji: '🈶', name: 'Japanese "not free of charge" button kanji' },
    { emoji: '🈯', name: 'Japanese "reserved" button kanji' },
    { emoji: '🈳', name: 'Japanese "vacancy" button kanji' },
    { emoji: '🈴', name: 'Japanese "passing grade" button kanji' },
    { emoji: '🈵', name: 'Japanese "no vacancy" button kanji' },
    { emoji: '🈹', name: 'Japanese "discount" button kanji' },
    { emoji: '🈺', name: 'Japanese "open for business" button kanji' },
    { emoji: '🉐', name: 'Japanese "bargain" button kanji' },
    { emoji: '🉑', name: 'Japanese "acceptable" button kanji' },
    { emoji: '🅰️', name: 'A button blood type letter' },
    { emoji: '🅱️', name: 'B button blood type letter' },
    { emoji: '🅾️', name: 'O button blood type letter' },
    { emoji: '🅿️', name: 'P button parking' },
    { emoji: '🆘', name: 'SOS button emergency help mayday' },
    { emoji: '⚠️', name: 'warning caution alert danger triangle' },
    { emoji: '⛔', name: 'no entry prohibited forbidden' },
    { emoji: '♨️', name: 'hot springs steam bathing onsen' },
    { emoji: '♻️', name: 'recycling symbol recycle environment green' },
    { emoji: '⚕️', name: 'medical symbol staff rod asklepios healthcare' },
    { emoji: '🏧', name: 'ATM sign money bank cash withdrawal' },
    { emoji: '🚮', name: 'litter in bin sign dispose trash garbage' },
    { emoji: '🚰', name: 'potable water sign drinking drinkable' },
    { emoji: '🚹', name: 'male room sign restroom bathroom toilet' },
    { emoji: '🚺', name: 'female room sign restroom bathroom toilet' },
    { emoji: '🚻', name: 'restroom sign toilet bathroom wc' },
    { emoji: '🚼', name: 'baby symbol child infant' },
    { emoji: '🚾', name: 'water closet toilet bathroom restroom wc' },
    { emoji: '🛂', name: 'passport control border customs immigration' },
    { emoji: '🛃', name: 'customs border declaration baggage' },
    { emoji: '🛄', name: 'baggage claim luggage suitcase airport' },
    { emoji: '🛅', name: 'left luggage storage locker' },
    { emoji: '🚸', name: 'children crossing school zone warning' },
    { emoji: '⛔', name: 'no entry forbidden prohibited' },
    { emoji: '🚫', name: 'prohibited no forbidden ban' },
    { emoji: '🚳', name: 'no bicycles forbidden prohibited' },
    { emoji: '🚭', name: 'no smoking forbidden prohibited cigarette' },
    { emoji: '🚯', name: 'no littering forbidden prohibited trash' },
    { emoji: '🚱', name: 'non potable water not drinkable' },
    { emoji: '🚷', name: 'no pedestrians forbidden prohibited walking' },
    { emoji: '🔞', name: 'no one under eighteen 18 adult only xxx' },
    { emoji: '☢️', name: 'radioactive danger nuclear warning' },
    { emoji: '☣️', name: 'biohazard danger warning biological' },
    { emoji: '⬆️', name: 'up arrow direction pointer' },
    { emoji: '↗️', name: 'up right arrow direction pointer' },
    { emoji: '➡️', name: 'right arrow direction pointer' },
    { emoji: '↘️', name: 'down right arrow direction pointer' },
    { emoji: '⬇️', name: 'down arrow direction pointer' },
    { emoji: '↙️', name: 'down left arrow direction pointer' },
    { emoji: '⬅️', name: 'left arrow direction pointer' },
    { emoji: '↖️', name: 'up left arrow direction pointer' },
    { emoji: '↕️', name: 'up down arrow direction vertical' },
    { emoji: '↔️', name: 'left right arrow direction horizontal' },
    { emoji: '↩️', name: 'right arrow curving left return back' },
    { emoji: '↪️', name: 'left arrow curving right forward continue' },
    { emoji: '⤴️', name: 'right arrow curving up direction' },
    { emoji: '⤵️', name: 'right arrow curving down direction' },
    { emoji: '🔃', name: 'clockwise vertical arrows refresh reload' },
    { emoji: '🔄', name: 'counterclockwise arrows button refresh reload' },
    { emoji: '🔙', name: 'back arrow previous return' },
    { emoji: '🔚', name: 'end arrow finish stop' },
    { emoji: '🔛', name: 'on! arrow continue go' },
    { emoji: '🔜', name: 'soon arrow future shortly' },
    { emoji: '🔝', name: 'top arrow up high best highest' },

    // Weather and Nature
    { emoji: '☀️', name: 'sun sunny weather hot bright sunshine' },
    { emoji: '🌤️', name: 'sun behind small cloud partly cloudy weather' },
    { emoji: '⛅', name: 'sun behind cloud partly cloudy weather' },
    { emoji: '🌥️', name: 'sun behind large cloud cloudy weather' },
    { emoji: '☁️', name: 'cloud cloudy weather overcast' },
    { emoji: '🌦️', name: 'sun behind rain cloud rainy weather' },
    { emoji: '🌧️', name: 'cloud with rain rainy weather wet' },
    { emoji: '⛈️', name: 'cloud with lightning and rain storm thunder weather' },
    { emoji: '🌩️', name: 'cloud with lightning storm thunder weather' },
    { emoji: '🌨️', name: 'cloud with snow snowfall cold weather' },
    { emoji: '❄️', name: 'snowflake snow cold weather winter' },
    { emoji: '☃️', name: 'snowman snow winter cold frosty' },
    { emoji: '⛄', name: 'snowman without snow frost winter cold' },
    { emoji: '🌬️', name: 'wind face blowing breeze air' },
    { emoji: '💨', name: 'dashing away wind dash running fast' },
    { emoji: '🌪️', name: 'tornado cyclone twister storm weather' },
    { emoji: '🌫️', name: 'fog mist weather cloud visibility' },
    { emoji: '☔', name: 'umbrella with rain drops wet shower weather' },
    { emoji: '⚡', name: 'high voltage lightning thunder electricity danger' },
    { emoji: '❄️', name: 'snowflake winter cold snow crystal' },
    { emoji: '☄️', name: 'comet space shooting star asteroid' },
    { emoji: '💧', name: 'droplet water drip sweat tear' },
    { emoji: '💦', name: 'droplet water drip sweat tear splash' },
    { emoji: '🌊', name: 'water wave sea ocean tsunami surf' },
    { emoji: '🌫️', name: 'fog foggy mist haze weather' },
    { emoji: '🌈', name: 'rainbow pride lgbtq colorful weather' },
    { emoji: '⛱️', name: 'umbrella on ground beach sunny shade' },
    { emoji: '☂️', name: 'umbrella rain shelter protection' },
    { emoji: '☔', name: 'umbrella with rain drops wet weather storm' },
    { emoji: '⛄', name: 'snowman without snow winter cold' },
    { emoji: '🌞', name: 'sun with face summer hot bright' },
    { emoji: '🌝', name: 'full moon with face night sky' },
    { emoji: '🌛', name: 'first quarter moon with face night sky' },
    { emoji: '🌜', name: 'last quarter moon with face night sky' },
    { emoji: '🌚', name: 'new moon with face night sky dark' },
    { emoji: '🌕', name: 'full moon night sky astronomy' },
    { emoji: '🌖', name: 'waning gibbous moon night sky astronomy' },
    { emoji: '🌗', name: 'last quarter moon night sky astronomy' },
    { emoji: '🌘', name: 'waning crescent moon night sky astronomy' },
    { emoji: '🌑', name: 'new moon night sky astronomy dark' },
    { emoji: '🌒', name: 'waxing crescent moon night sky astronomy' },
    { emoji: '🌓', name: 'first quarter moon night sky astronomy' },
    { emoji: '🌔', name: 'waxing gibbous moon night sky astronomy' },
    { emoji: '🌙', name: 'crescent moon night sky islam' },
    { emoji: '🌎', name: 'globe showing Americas earth world planet USA' },
    { emoji: '🌍', name: 'globe showing Europe Africa earth world planet Europe Africa' },
    { emoji: '🌏', name: 'globe showing Asia Australia earth world planet Asia Australia' },
    { emoji: '🌐', name: 'globe with meridians earth world planet international' },
    { emoji: '🪐', name: 'ringed planet saturn space astronomy' },
    { emoji: '🌋', name: 'volcano mountain eruption lava geology' },
    { emoji: '🌄', name: 'sunrise over mountains morning dawn daybreak' },
    { emoji: '🌅', name: 'sunrise morning dawn daybreak sun' },
    { emoji: '🌆', name: 'cityscape at dusk sunset city evening' },
    { emoji: '🌇', name: 'sunset city dusk evening' },
    { emoji: '🌉', name: 'bridge at night evening dark' },
    { emoji: '🌌', name: 'milky way galaxy stars space night' },
    { emoji: '🌠', name: 'shooting star wish falling star space' },
    { emoji: '🌁', name: 'foggy weather visibility fog mist' },
    { emoji: '🌃', name: 'night with stars evening nighttime starry' },
    { emoji: '🏞️', name: 'national park nature mountain forest' },
    { emoji: '🏜️', name: 'desert arid hot sand dry' },
    { emoji: '🏝️', name: 'desert island beach isolated coast' },
    { emoji: '🏖️', name: 'beach with umbrella sand sea vacation' },
    { emoji: '🗻', name: 'mount fuji mountain japan volcano' },
    { emoji: '⛰️', name: 'mountain highland peak summit' },
    { emoji: '🏔️', name: 'snow capped mountain alpine peak' },
    { emoji: '🏕️', name: 'camping outdoors tent adventure' },
    { emoji: '🏙️', name: 'cityscape buildings skyscrapers metropolis' },
    { emoji: '🪨', name: 'rock stone boulder mountain' },
    { emoji: '🪵', name: 'wood log timber lumber tree' },
    { emoji: '🛸', name: 'flying saucer UFO alien space' },

    // Time and Calendar
    { emoji: '📅', name: 'calendar date time schedule appointment' },
    { emoji: '📆', name: 'tear off calendar date time schedule' },
    { emoji: '🗓️', name: 'spiral calendar date time schedule planner' },
    { emoji: '⏰', name: 'alarm clock time wake up morning' },
    { emoji: '⏱️', name: 'stopwatch time timer race' },
    { emoji: '⏲️', name: 'timer clock time countdown' },
    { emoji: '🕰️', name: 'mantelpiece clock time antique vintage' },
    { emoji: '⌛', name: 'hourglass done time sand timer complete' },
    { emoji: '⏳', name: 'hourglass not done time sand timer waiting' },
    { emoji: '🕛', name: 'twelve oclock time noon midnight 12' },
    { emoji: '🕧', name: 'twelve thirty time 12:30 half past twelve' },
    { emoji: '🕐', name: 'one oclock time 1 hour' },
    { emoji: '🕜', name: 'one thirty time 1:30 half past one' },
    { emoji: '🕑', name: 'two oclock time 2 hour' },
    { emoji: '🕝', name: 'two thirty time 2:30 half past two' },
    { emoji: '🕒', name: 'three oclock time 3 hour' },
    { emoji: '🕞', name: 'three thirty time 3:30 half past three' },
    { emoji: '🕓', name: 'four oclock time 4 hour' },
    { emoji: '🕟', name: 'four thirty time 4:30 half past four' },
    { emoji: '🕔', name: 'five oclock time 5 hour' },
    { emoji: '🕠', name: 'five thirty time 5:30 half past five' },
    { emoji: '🕕', name: 'six oclock time 6 hour' },
    { emoji: '🕡', name: 'six thirty time 6:30 half past six' },
    { emoji: '🕖', name: 'seven oclock time 7 hour' },
    { emoji: '🕢', name: 'seven thirty time 7:30 half past seven' },
    { emoji: '🕗', name: 'eight oclock time 8 hour' },
    { emoji: '🕣', name: 'eight thirty time 8:30 half past eight' },
    { emoji: '🕘', name: 'nine oclock time 9 hour' },
    { emoji: '🕤', name: 'nine thirty time 9:30 half past nine' },
    { emoji: '🕙', name: 'ten oclock time 10 hour' },
    { emoji: '🕥', name: 'ten thirty time 10:30 half past ten' },
    { emoji: '🕚', name: 'eleven oclock time 11 hour' },
    { emoji: '🕦', name: 'eleven thirty time 11:30 half past eleven' },

    // Transportation
    { emoji: '🚗', name: 'car automobile vehicle drive transport' },
    { emoji: '🚕', name: 'taxi cab rideshare vehicle transportation' },
    { emoji: '🚙', name: 'sport utility vehicle suv car jeep' },
    { emoji: '🚌', name: 'bus vehicle transportation public' },
    { emoji: '🚎', name: 'trolleybus vehicle transportation public' },
    { emoji: '🏎️', name: 'racing car fast formula1 f1 speed' },
    { emoji: '🚓', name: 'police car law enforcement vehicle cops' },
    { emoji: '🚑', name: 'ambulance medical emergency vehicle 911' },
    { emoji: '🚒', name: 'fire engine truck firefighter emergency' },
    { emoji: '🚐', name: 'minibus vehicle transportation shuttle' },
    { emoji: '🚚', name: 'delivery truck vehicle shipping transport' },
    { emoji: '🚛', name: 'articulated lorry truck vehicle transport' },
    { emoji: '🚜', name: 'tractor vehicle farm agriculture' },
    { emoji: '🛻', name: 'pickup truck vehicle transportation' },
    { emoji: '🏍️', name: 'motorcycle bike vehicle racing' },
    { emoji: '🛵', name: 'motor scooter vehicle vespa transportation' },
    { emoji: '🛺', name: 'auto rickshaw vehicle tuk tuk transportation' },
    { emoji: '🚲', name: 'bicycle bike cycle vehicle transportation' },
    { emoji: '🛴', name: 'kick scooter vehicle transportation' },
    { emoji: '🚏', name: 'bus stop transportation public' },
    { emoji: '🛣️', name: 'motorway highway road freeway' },
    { emoji: '🛤️', name: 'railway track train transportation' },
    { emoji: '⛽', name: 'fuel pump gas petroleum gasoline' },
    { emoji: '🚨', name: 'police car light emergency siren' },
    { emoji: '🚥', name: 'horizontal traffic light stoplight' },
    { emoji: '🚦', name: 'vertical traffic light stoplight' },
    { emoji: '🚧', name: 'construction sign warning caution barrier' },
    { emoji: '⚓', name: 'anchor ship boat marina harbor' },
    { emoji: '⛵', name: 'sailboat boat yacht sailing' },
    { emoji: '🚤', name: 'speedboat boat ship' },
    { emoji: '🚢', name: 'ship boat cruise ferry' },
    { emoji: '✈️', name: 'airplane flight plane flying aviation air travel jet' },
    { emoji: '🛩️', name: 'small airplane flight aviation' },
    { emoji: '🛫', name: 'airplane departure takeoff flight flying' },
    { emoji: '🛬', name: 'airplane arrival landing flight flying' },
    { emoji: '🪂', name: 'parachute skydive flying' },
    { emoji: '💺', name: 'seat chair sitting' },
    { emoji: '🚁', name: 'helicopter aircraft chopper flying' },
    { emoji: '🚟', name: 'suspension railway transportation' },
    { emoji: '🚠', name: 'mountain cableway transportation' },
    { emoji: '🚡', name: 'aerial tramway transportation' },
    { emoji: '🚀', name: 'rocket spaceship launch space blast rocketship' },
    { emoji: '🛸', name: 'flying saucer ufo alien space' },
    { emoji: '🚉', name: 'station train subway metro transportation' },
    { emoji: '🚂', name: 'locomotive train steam engine transportation railway' },
    { emoji: '🚆', name: 'train transportation vehicle railway' },
    { emoji: '🚇', name: 'metro subway train transportation' },
    { emoji: '🚊', name: 'tram transportation vehicle' },
    { emoji: '🚝', name: 'monorail transportation train' },
    { emoji: '🚞', name: 'mountain railway transportation train' },
    { emoji: '🚋', name: 'tram car transportation vehicle' },
    { emoji: '🚃', name: 'railway car transportation train' },
    { emoji: '🚄', name: 'high speed train bullet transportation' },
    { emoji: '🚅', name: 'bullet train high speed bullet transportation' },
    { emoji: '🚈', name: 'light rail transportation train' },
    { emoji: '🛑', name: 'stop sign octagon halt traffic' },
    { emoji: '🚧', name: 'construction sign warning caution' },
    { emoji: '⚠️', name: 'warning sign caution alert danger' },

    // Sports and Activities
    { emoji: '⚽', name: 'soccer ball football sport sports game' },
    { emoji: '🏀', name: 'basketball ball sport hoops nba' },
    { emoji: '🏈', name: 'american football ball sport nfl game' },
    { emoji: '⚾', name: 'baseball ball sport mlb game' },
    { emoji: '🥎', name: 'softball ball sport game' },
    { emoji: '🎾', name: 'tennis ball sport game racket' },
    { emoji: '🏐', name: 'volleyball ball sport game' },
    { emoji: '🏉', name: 'rugby football ball sport game' },
    { emoji: '🥏', name: 'flying disc frisbee ultimate sport' },
    { emoji: '🎱', name: 'pool 8 ball billiards snooker game' },
    { emoji: '🪀', name: 'yo yo toy play spin string' },
    { emoji: '🏓', name: 'ping pong table tennis paddle ball sport' },
    { emoji: '🏸', name: 'badminton racket shuttlecock sport' },
    { emoji: '🏒', name: 'ice hockey stick and puck sport nhl game' },
    { emoji: '🏑', name: 'field hockey stick and ball sport game' },
    { emoji: '🥍', name: 'lacrosse stick and ball sport' },
    { emoji: '🏏', name: 'cricket game bat ball sport' },
    { emoji: '🥅', name: 'goal net hockey soccer football sport' },
    { emoji: '⛳', name: 'flag in hole golf sport' },
    { emoji: '⛸️', name: 'ice skate skating winter sport' },
    { emoji: '🎣', name: 'fishing pole rod fish catch' },
    { emoji: '🤿', name: 'diving mask snorkel underwater scuba' },
    { emoji: '🎽', name: 'running shirt athletics jersey' },
    { emoji: '🎿', name: 'skis skiing winter snow sport' },
    { emoji: '🛷', name: 'sleigh snowsled winter snow sport' },
    { emoji: '🥌', name: 'curling stone winter sport olympics' },
    { emoji: '🎯', name: 'direct hit bullseye target darts game' },
    { emoji: '🪄', name: 'magic wand wizard magic magician' },
    { emoji: '🪃', name: 'boomerang throw return australian' },
    { emoji: '🏹', name: 'bow and arrow archery sport shooting' },
    { emoji: '🎣', name: 'fishing pole rod fish catch sport' },
    { emoji: '🤿', name: 'diving mask snorkel scuba underwater' },
    { emoji: '🥊', name: 'boxing glove sport fighting punch' },
    { emoji: '🥋', name: 'martial arts uniform karate judo sport' },
    { emoji: '🎮', name: 'video game controller play gaming gaming' },
    { emoji: '🎲', name: 'game die dice gambling random' },
    { emoji: '♟️', name: 'chess pawn board game strategy' },
    { emoji: '🎭', name: 'performing arts theater drama masks' },
    { emoji: '🎨', name: 'artist palette art painting drawing' },
    { emoji: '🎬', name: 'clapper board movie film director' },
    { emoji: '🎤', name: 'microphone sing karaoke music' },
    { emoji: '🎧', name: 'headphone music listen audio' },
    { emoji: '🎼', name: 'musical score notes sheet music' },
    { emoji: '🎹', name: 'musical keyboard piano organ instrument' },
    { emoji: '🪕', name: 'banjo instrument music string' },
    { emoji: '🎸', name: 'guitar instrument music rock string' },
    { emoji: '🎻', name: 'violin instrument music string' },
    { emoji: '🎺', name: 'trumpet instrument music brass' },
    { emoji: '🎷', name: 'saxophone instrument music jazz' },
    { emoji: '🥁', name: 'drum instrument music percussion' },
    { emoji: '🪘', name: 'long drum instrument music rhythm' },
    { emoji: '🎵', name: 'musical note music tone sound' },
    { emoji: '🎶', name: 'musical notes music melody sound' },
    { emoji: '🏋️', name: 'person lifting weights gym exercise strength' },
    { emoji: '🏊', name: 'swimmer swimming water pool sport' },
    { emoji: '🤽', name: 'person playing water polo swimming sport' },
    { emoji: '🤾', name: 'person playing handball sport ball' },
    { emoji: '🏌️', name: 'person golfing golfer sport' },
    { emoji: '🧘', name: 'person in lotus position yoga meditation zen' },
    { emoji: '🚴', name: 'person biking cyclist bicycle sport' },
    { emoji: '🧗', name: 'person climbing rock climber sport' },
    { emoji: '🤺', name: 'person fencing sword fight sport' },
    { emoji: '🏇', name: 'horse racing jockey derby sport' },
    { emoji: '🏄', name: 'person surfing surfer wave sport' },
    { emoji: '🚣', name: 'person rowing boat row sport' },
    { emoji: '🪂', name: 'parachute skydiving flying extreme' },
    { emoji: '🏂', name: 'snowboarder snowboarding winter sport' },
    { emoji: '⛷️', name: 'skier skiing winter sport' },
    { emoji: '🏆', name: 'trophy prize winning champion award' },
    { emoji: '🥇', name: 'gold medal first champion award' },
    { emoji: '🥈', name: 'silver medal second place award' },
    { emoji: '🥉', name: 'bronze medal third place award' },
    { emoji: '🏅', name: 'sports medal award prize medal' },
    { emoji: '🎖️', name: 'military medal award honor decoration' },
    { emoji: '🏵️', name: 'rosette flower decoration' },
    { emoji: '🎗️', name: 'reminder ribbon cause awareness' },
    { emoji: '🎫', name: 'ticket admission pass event' },
    
    // Buildings and Places
    { emoji: '🏠', name: 'house building home residence' },
    { emoji: '🏡', name: 'house with garden home yard lawn' },
    { emoji: '🏢', name: 'office building work corporate business' },
    { emoji: '🏣', name: 'Japanese post office mail postal' },
    { emoji: '🏤', name: 'post office mail postal' },
    { emoji: '🏥', name: 'hospital health emergency medical sick' },
    { emoji: '🏦', name: 'bank money financial building' },
    { emoji: '🏨', name: 'hotel building lodging accommodation' },
    { emoji: '🏩', name: 'love hotel heart romance building' },
    { emoji: '🏪', name: 'convenience store building 7 eleven' },
    { emoji: '🏫', name: 'school building education student' },
    { emoji: '🏬', name: 'department store building shopping mall' },
    { emoji: '🏭', name: 'factory building industrial manufacturing' },
    { emoji: '🏯', name: 'japanese castle building fortress palace' },
    { emoji: '🏰', name: 'castle building fortress palace medieval' },
    { emoji: '💒', name: 'wedding chapel church marriage love' },
    { emoji: '🗼', name: 'tokyo tower landmark Japan' },
    { emoji: '🗽', name: 'Statue of Liberty USA America New York' },
    { emoji: '⛪', name: 'church building christian religion cross' },
    { emoji: '🛕', name: 'hindu temple building religion jagannath' },
    { emoji: '🕍', name: 'synagogue building judaism jewish religion' },
    { emoji: '⛩️', name: 'shinto shrine building religion Japanese' },
    { emoji: '⛲', name: 'fountain water park decoration' },
    { emoji: '⛺', name: 'tent camping outdoors festival' },
    { emoji: '🌁', name: 'foggy cityscape mist visibility' },
    { emoji: '🌃', name: 'night with stars evening city dark starry' },
    { emoji: '🏙️', name: 'cityscape buildings urban skyscrapers' },
    { emoji: '🌄', name: 'sunrise over mountains morning dawn' },
    { emoji: '🌅', name: 'sunrise morning dawn daybreak' },
    { emoji: '🌆', name: 'cityscape at dusk evening sunset' },
    { emoji: '🌇', name: 'sunset evening dusk sun' },
    { emoji: '🌉', name: 'bridge at night evening dark' },
    { emoji: '🎠', name: 'carousel horse amusement park ride' },
    { emoji: '🎡', name: 'ferris wheel amusement park carnival' },
    { emoji: '🎢', name: 'roller coaster amusement park carnival ride' },
    { emoji: '🚂', name: 'locomotive train steam engine railroad' },
    { emoji: '💈', name: 'barber pole haircut salon' },
    { emoji: '🎪', name: 'circus tent festival carnival big top' },
    
    // Music and Arts
    { emoji: '🎵', name: 'musical note music sound tone melody' },
    { emoji: '🎶', name: 'musical notes music melody sound sing' },
    { emoji: '🎙️', name: 'studio microphone recording podcast audio' },
    { emoji: '🎚️', name: 'level slider control audio mixing' },
    { emoji: '🎛️', name: 'control knobs dial mix audio adjustment' },
    { emoji: '🎤', name: 'microphone sing karaoke voice audio' },
    { emoji: '🎧', name: 'headphone music listen audio earphones' },
    { emoji: '📻', name: 'radio audio broadcast tuner music' },
    { emoji: '🎷', name: 'saxophone instrument jazz blues music' },
    { emoji: '🪗', name: 'accordion instrument music squeeze box' },
    { emoji: '🎸', name: 'guitar instrument music rock string' },
    { emoji: '🎹', name: 'musical keyboard piano organ instrument keys' },
    { emoji: '🎺', name: 'trumpet instrument music brass' },
    { emoji: '🎻', name: 'violin instrument music string orchestra' },
    { emoji: '🥁', name: 'drum percussion instrument music beat' },
    { emoji: '🪘', name: 'long drum instrument music percussion' },
    { emoji: '🪕', name: 'banjo string instrument music country' },
    { emoji: '🎭', name: 'performing arts theater drama masks acting' },
    { emoji: '🎨', name: 'artist palette paint drawing art colors' },
    { emoji: '🧵', name: 'thread sewing craft string spool' },
    { emoji: '🧶', name: 'yarn knitting crochet craft wool' },
    { emoji: '🪡', name: 'sewing needle thread craft stitch' },
    { emoji: '🖼️', name: 'framed picture painting art museum gallery' },
    { emoji: '🎬', name: 'clapper board movie film director action' },
    { emoji: '🎮', name: 'video game controller play gaming esports' },
    { emoji: '🕹️', name: 'joystick gaming controller arcade' },
    { emoji: '🎲', name: 'game die dice random gambling board game' },
    { emoji: '♟️', name: 'chess pawn strategy board game' },
    { emoji: '🎴', name: 'flower playing cards game hanafuda' },
    { emoji: '🀄', name: 'mahjong red dragon game tiles' },
    { emoji: '🎯', name: 'direct hit target bullseye darts game' },
    { emoji: '🎪', name: 'circus tent entertainment carnival' },
    { emoji: '🖍️', name: 'crayon drawing art coloring' },
    { emoji: '🖌️', name: 'paintbrush art painting drawing' },
    
    // Technology and Science
    { emoji: '💻', name: 'laptop computer pc tech notebook' },
    { emoji: '🖥️', name: 'desktop computer pc monitor tech' },
    { emoji: '🖨️', name: 'printer device output office' },
    { emoji: '⌨️', name: 'keyboard typing input device' },
    { emoji: '🖱️', name: 'computer mouse input device click' },
    { emoji: '🖲️', name: 'trackball input device pointer' },
    { emoji: '💽', name: 'computer disk storage minidisc' },
    { emoji: '💾', name: 'floppy disk save old storage' },
    { emoji: '💿', name: 'optical disk cd dvd storage' },
    { emoji: '📀', name: 'dvd disk storage movie film' },
    { emoji: '🧮', name: 'abacus calculation math counting' },
    { emoji: '🎥', name: 'movie camera film video recording' },
    { emoji: '🎞️', name: 'film frames movie cinema' },
    { emoji: '📽️', name: 'film projector movie cinema' },
    { emoji: '🎬', name: 'clapper board movie director action film' },
    { emoji: '📺', name: 'television tv screen broadcast' },
    { emoji: '📷', name: 'camera photo photography picture' },
    { emoji: '📸', name: 'camera with flash photography picture' },
    { emoji: '📹', name: 'video camera recording film movie' },
    { emoji: '📼', name: 'videocassette vhs tape video' },
    { emoji: '🔍', name: 'magnifying glass tilted left search zoom' },
    { emoji: '🔎', name: 'magnifying glass tilted right search zoom' },
    { emoji: '🕯️', name: 'candle light wax flame' },
    { emoji: '💡', name: 'light bulb idea bright electricity' },
    { emoji: '🔦', name: 'flashlight torch light portable' },
    { emoji: '🔆', name: 'bright button light sun' },
    { emoji: '🔅', name: 'dim button low light brightness' },
    { emoji: '🔋', name: 'battery power energy charge' },
    { emoji: '🔌', name: 'electric plug power outlet electricity' },
    { emoji: '📡', name: 'satellite antenna dish signal reception' },
    { emoji: '⏳', name: 'hourglass not done time sand waiting' },
    { emoji: '⌛', name: 'hourglass done time sand complete' },
    { emoji: '⏰', name: 'alarm clock time morning wakeup' },
    { emoji: '⏱️', name: 'stopwatch time timer precision' },
    { emoji: '⏲️', name: 'timer clock time countdown cooking' },
    { emoji: '🧮', name: 'abacus calculate counting math' },
    { emoji: '🔬', name: 'microscope science laboratory research' },
    { emoji: '🔭', name: 'telescope astronomy space stars' },
    { emoji: '📱', name: 'mobile phone smartphone iphone android cell' },
    { emoji: '📲', name: 'mobile phone with arrow call download' },
    { emoji: '☎️', name: 'telephone phone call landline' },
    { emoji: '📞', name: 'telephone receiver handset phone call' },
    { emoji: '📠', name: 'fax machine office document send' },
    { emoji: '📟', name: 'pager device message beeper' },
    { emoji: '📻', name: 'radio music broadcast audio' },
    { emoji: '🧪', name: 'test tube science chemistry laboratory' },
    { emoji: '🧫', name: 'petri dish science biology laboratory bacteria' },
    { emoji: '🧬', name: 'dna science genetics biology helix' },
    { emoji: '💊', name: 'pill medicine drug health medication pharmacy' },
    { emoji: '💉', name: 'syringe shot injection vaccine medicine needle' },
    { emoji: '🩸', name: 'drop of blood bleed donation injury' },
    { emoji: '🩹', name: 'adhesive bandage bandaid injury plaster' },
    { emoji: '🩺', name: 'stethoscope doctor nurse health medical' },
    { emoji: '🪒', name: 'razor shave blade barber' },
    { emoji: '🧮', name: 'abacus calculation math counting' },
    
    // Zodiac and Astrology
    { emoji: '♈', name: 'aries zodiac horoscope astrology ram march april' },
    { emoji: '♉', name: 'taurus zodiac horoscope astrology bull april may' },
    { emoji: '♊', name: 'gemini zodiac horoscope astrology twins may june' },
    { emoji: '♋', name: 'cancer zodiac horoscope astrology crab june july' },
    { emoji: '♌', name: 'leo zodiac horoscope astrology lion july august' },
    { emoji: '♍', name: 'virgo zodiac horoscope astrology maiden august september' },
    { emoji: '♎', name: 'libra zodiac horoscope astrology scales september october' },
    { emoji: '♏', name: 'scorpio zodiac horoscope astrology scorpion october november' },
    { emoji: '♐', name: 'sagittarius zodiac horoscope astrology archer november december' },
    { emoji: '♑', name: 'capricorn zodiac horoscope astrology goat december january' },
    { emoji: '♒', name: 'aquarius zodiac horoscope astrology water bearer january february' },
    { emoji: '♓', name: 'pisces zodiac horoscope astrology fish february march' },
    { emoji: '⛎', name: 'ophiuchus zodiac horoscope astrology serpent bearer' },

    // Flags
    { emoji: '🏁', name: 'chequered flag racing motorsport finish checkered race f1 formula1 nascar' },
    { emoji: '🚩', name: 'triangular flag post location marker pin red warning' },
    { emoji: '🎌', name: 'crossed flags japan ceremony celebration festival nippon japanese' },
    { emoji: '🏴', name: 'black flag pirate dark waving' },
    { emoji: '🏳️', name: 'white flag surrender truce peace giving up' },
    { emoji: '🏴‍☠️', name: 'pirate flag skull crossbones jolly roger buccaneer caribbean' },
    { emoji: '🇦🇨', name: 'flag ascension island ac' },
    { emoji: '🇦🇩', name: 'flag andorra ad andorran' },
    { emoji: '🇦🇪', name: 'flag united arab emirates uae emirati dubai abu dhabi' },
    { emoji: '🇦🇫', name: 'flag afghanistan af afghan' },
    { emoji: '🇦🇬', name: 'flag antigua & barbuda ag antiguan barbudan' },
    { emoji: '🇦🇮', name: 'flag anguilla ai' },
    { emoji: '🇦🇱', name: 'flag albania al albanian' },
    { emoji: '🇦🇲', name: 'flag armenia am armenian' },
    { emoji: '🇦🇴', name: 'flag angola ao angolan' },
    { emoji: '🇦🇶', name: 'flag antarctica aq antarctic south pole' },
    { emoji: '🇦🇷', name: 'flag argentina ar argentinian argentinean' },
    { emoji: '🇦🇸', name: 'flag american samoa as samoan' },
    { emoji: '🇦🇹', name: 'flag austria at austrian vienna' },
    { emoji: '🇦🇺', name: 'flag australia au aussie australian oz sydney melbourne' },
    { emoji: '🇦🇼', name: 'flag aruba aw aruban' },
    { emoji: '🇦🇽', name: 'flag åland islands ax aland' },
    { emoji: '🇦🇿', name: 'flag azerbaijan az azerbaijani azeri' },
    { emoji: '🇧🇦', name: 'flag bosnia & herzegovina ba bosnian herzegovinian' },
    { emoji: '🇧🇧', name: 'flag barbados bb barbadian bajan' },
    { emoji: '🇧🇩', name: 'flag bangladesh bd bangladeshi bengali' },
    { emoji: '🇧🇪', name: 'flag belgium be belgian flemish' },
    { emoji: '🇧🇫', name: 'flag burkina faso bf burkinabe' },
    { emoji: '🇧🇬', name: 'flag bulgaria bg bulgarian' },
    { emoji: '🇧🇭', name: 'flag bahrain bh bahraini' },
    { emoji: '🇧🇮', name: 'flag burundi bi burundian' },
    { emoji: '🇧🇯', name: 'flag benin bj beninese' },
    { emoji: '🇧🇱', name: 'flag st. barthélemy bl saint barthelemy' },
    { emoji: '🇧🇲', name: 'flag bermuda bm bermudan' },
    { emoji: '🇧🇳', name: 'flag brunei bn bruneian' },
    { emoji: '🇧🇴', name: 'flag bolivia bo bolivian' },
    { emoji: '🇧🇶', name: 'flag caribbean netherlands bq bonaire st eustatius saba' },
    { emoji: '🇧🇷', name: 'flag brazil br brazilian brasil rio sao paulo' },
    { emoji: '🇧🇸', name: 'flag bahamas bs bahamian' },
    { emoji: '🇧🇹', name: 'flag bhutan bt bhutanese' },
    { emoji: '🇧🇻', name: 'flag bouvet island bv' },
    { emoji: '🇧🇼', name: 'flag botswana bw motswana batswana' },
    { emoji: '🇧🇾', name: 'flag belarus by belarusian' },
    { emoji: '🇧🇿', name: 'flag belize bz belizean' },
    { emoji: '🇨🇦', name: 'flag canada ca canadian maple leaf toronto ottawa' },
    { emoji: '🇨🇨', name: 'flag cocos (keeling) islands cc' },
    { emoji: '🇨🇩', name: 'flag congo - kinshasa cd drc democratic republic congo' },
    { emoji: '🇨🇫', name: 'flag central african republic cf car' },
    { emoji: '🇨🇬', name: 'flag congo - brazzaville cg republic congo' },
    { emoji: '🇨🇭', name: 'flag switzerland ch swiss suisse zurich geneva' },
    { emoji: '🇨🇮', name: 'flag côte d\'ivoire ci ivory coast ivorian' },
    { emoji: '🇨🇰', name: 'flag cook islands ck' },
    { emoji: '🇨🇱', name: 'flag chile cl chilean' },
    { emoji: '🇨🇲', name: 'flag cameroon cm cameroonian' },
    { emoji: '🇨🇳', name: 'flag china cn chinese prc beijing shanghai' },
    { emoji: '🇨🇴', name: 'flag colombia co colombian' },
    { emoji: '🇨🇵', name: 'flag clipperton island cp' },
    { emoji: '🇨🇷', name: 'flag costa rica cr costa rican' },
    { emoji: '🇨🇺', name: 'flag cuba cu cuban' },
    { emoji: '🇨🇻', name: 'flag cape verde cv cabo verde cabo verdean' },
    { emoji: '🇨🇼', name: 'flag curaçao cw curacao' },
    { emoji: '🇨🇽', name: 'flag christmas island cx' },
    { emoji: '🇨🇾', name: 'flag cyprus cy cypriot' },
    { emoji: '🇨🇿', name: 'flag czechia cz czech republic prague' },
    { emoji: '🇩🇪', name: 'flag germany de german deutsch berlin munich' },
    { emoji: '🇩🇬', name: 'flag diego garcia dg' },
    { emoji: '🇩🇯', name: 'flag djibouti dj djiboutian' },
    { emoji: '🇩🇰', name: 'flag denmark dk danish dane copenhagen' },
    { emoji: '🇩🇲', name: 'flag dominica dm dominican' },
    { emoji: '🇩🇴', name: 'flag dominican republic do dominican' },
    { emoji: '🇩🇿', name: 'flag algeria dz algerian' },
    { emoji: '🇪🇦', name: 'flag ceuta & melilla ea' },
    { emoji: '🇪🇨', name: 'flag ecuador ec ecuadorian' },
    { emoji: '🇪🇪', name: 'flag estonia ee estonian' },
    { emoji: '🇪🇬', name: 'flag egypt eg egyptian' },
    { emoji: '🇪🇭', name: 'flag western sahara eh sahrawi' },
    { emoji: '🇪🇷', name: 'flag eritrea er eritrean' },
    { emoji: '🇪🇸', name: 'flag spain es spanish espana espanol madrid barcelona' },
    { emoji: '🇪🇹', name: 'flag ethiopia et ethiopian' },
    { emoji: '🇪🇺', name: 'flag european union eu europe brussels' },
    { emoji: '🇫🇮', name: 'flag finland fi finnish finn helsinki' },
    { emoji: '🇫🇯', name: 'flag fiji fj fijian' },
    { emoji: '🇫🇰', name: 'flag falkland islands fk malvinas' },
    { emoji: '🇫🇲', name: 'flag micronesia fm micronesian' },
    { emoji: '🇫🇴', name: 'flag faroe islands fo faroese' },
    { emoji: '🇫🇷', name: 'flag france fr french paris marseille' },
    { emoji: '🇬🇦', name: 'flag gabon ga gabonese' },
    { emoji: '🇬🇧', name: 'flag united kingdom gb uk britain british england english london' },
    { emoji: '🇬🇩', name: 'flag grenada gd grenadian' },
    { emoji: '🇬🇪', name: 'flag georgia ge georgian' },
    { emoji: '🇬🇫', name: 'flag french guiana gf' },
    { emoji: '🇬🇬', name: 'flag guernsey gg' },
    { emoji: '🇬🇭', name: 'flag ghana gh ghanaian' },
    { emoji: '🇬🇮', name: 'flag gibraltar gi gibraltarian' },
    { emoji: '🇬🇱', name: 'flag greenland gl greenlandic' },
    { emoji: '🇬🇲', name: 'flag gambia gm gambian' },
    { emoji: '🇬🇳', name: 'flag guinea gn guinean' },
    { emoji: '🇬🇵', name: 'flag guadeloupe gp' },
    { emoji: '🇬🇶', name: 'flag equatorial guinea gq equatoguinean' },
    { emoji: '🇬🇷', name: 'flag greece gr greek hellenic athens' },
    { emoji: '🇬🇸', name: 'flag south georgia & south sandwich islands gs' },
    { emoji: '🇬🇹', name: 'flag guatemala gt guatemalan' },
    { emoji: '🇬🇺', name: 'flag guam gu guamanian chamorro' },
    { emoji: '🇬🇼', name: 'flag guinea-bissau gw bissau-guinean' },
    { emoji: '🇬🇾', name: 'flag guyana gy guyanese' },
    { emoji: '🇭🇰', name: 'flag hong kong sar china hk hongkong hongkonger' },
    { emoji: '🇭🇲', name: 'flag heard & mcdonald islands hm' },
    { emoji: '🇭🇳', name: 'flag honduras hn honduran' },
    { emoji: '🇭🇷', name: 'flag croatia hr croatian croat' },
    { emoji: '🇭🇹', name: 'flag haiti ht haitian' },
    { emoji: '🇭🇺', name: 'flag hungary hu hungarian magyar' },
    { emoji: '🇮🇨', name: 'flag canary islands ic' },
    { emoji: '🇮🇩', name: 'flag indonesia id indonesian jakarta' },
    { emoji: '🇮🇪', name: 'flag ireland ie irish eire dublin' },
    { emoji: '🇮🇱', name: 'flag israel il israeli tel aviv jerusalem' },
    { emoji: '🇮🇲', name: 'flag isle of man im manx' },
    { emoji: '🇮🇳', name: 'flag india in indian delhi mumbai' },
    { emoji: '🇮🇴', name: 'flag british indian ocean territory io biot' },
    { emoji: '🇮🇶', name: 'flag iraq iq iraqi' },
    { emoji: '🇮🇷', name: 'flag iran ir iranian persian' },
    { emoji: '🇮🇸', name: 'flag iceland is icelandic icelander reykjavik' },
    { emoji: '🇮🇹', name: 'flag italy it italian italia rome milan' },
    { emoji: '🇯🇪', name: 'flag jersey je' },
    { emoji: '🇯🇲', name: 'flag jamaica jm jamaican' },
    { emoji: '🇯🇴', name: 'flag jordan jo jordanian' },
    { emoji: '🇯🇵', name: 'flag japan jp japanese nippon tokyo osaka' },
    { emoji: '🇰🇪', name: 'flag kenya ke kenyan' },
    { emoji: '🇰🇬', name: 'flag kyrgyzstan kg kyrgyz' },
    { emoji: '🇰🇭', name: 'flag cambodia kh cambodian khmer' },
    { emoji: '🇰🇮', name: 'flag kiribati ki i-kiribati' },
    { emoji: '🇰🇲', name: 'flag comoros km comoran' },
    { emoji: '🇰🇳', name: 'flag st. kitts & nevis kn saint kitts and nevis kittitian nevisian' },
    { emoji: '🇰🇵', name: 'flag north korea kp dprk democratic peoples republic korea korean pyongyang' },
    { emoji: '🇰🇷', name: 'flag south korea kr republic korea korean seoul' },
    { emoji: '🇰🇼', name: 'flag kuwait kw kuwaiti' },
    { emoji: '🇰🇾', name: 'flag cayman islands ky caymanian' },
    { emoji: '🇰🇿', name: 'flag kazakhstan kz kazakh' },
    { emoji: '🇱🇦', name: 'flag laos la lao laotian' },
    { emoji: '🇱🇧', name: 'flag lebanon lb lebanese' },
    { emoji: '🇱🇨', name: 'flag st. lucia lc saint lucia saint lucian' },
    { emoji: '🇱🇮', name: 'flag liechtenstein li liechtensteiner' },
    { emoji: '🇱🇰', name: 'flag sri lanka lk sri lankan' },
    { emoji: '🇱🇷', name: 'flag liberia lr liberian' },
    { emoji: '🇱🇸', name: 'flag lesotho ls mosotho basotho' },
    { emoji: '🇱🇹', name: 'flag lithuania lt lithuanian' },
    { emoji: '🇱🇺', name: 'flag luxembourg lu luxembourger luxembourgish' },
    { emoji: '🇱🇻', name: 'flag latvia lv latvian' },
    { emoji: '🇱🇾', name: 'flag libya ly libyan' },
    { emoji: '🇲🇦', name: 'flag morocco ma moroccan' },
    { emoji: '🇲🇨', name: 'flag monaco mc monegasque monacan' },
    { emoji: '🇲🇩', name: 'flag moldova md moldovan' },
    { emoji: '🇲🇪', name: 'flag montenegro me montenegrin' },
    { emoji: '🇲🇫', name: 'flag st. martin mf saint martin' },
    { emoji: '🇲🇬', name: 'flag madagascar mg malagasy' },
    { emoji: '🇲🇭', name: 'flag marshall islands mh marshallese' },
    { emoji: '🇲🇰', name: 'flag north macedonia mk macedonian' },
    { emoji: '🇲🇱', name: 'flag mali ml malian' },
    { emoji: '🇲🇲', name: 'flag myanmar burma mm burmese' },
    { emoji: '🇲🇳', name: 'flag mongolia mn mongolian' },
    { emoji: '🇲🇴', name: 'flag macao sar china mo macau macanese' },
    { emoji: '🇲🇵', name: 'flag northern mariana islands mp' },
    { emoji: '🇲🇶', name: 'flag martinique mq martiniquais' },
    { emoji: '🇲🇷', name: 'flag mauritania mr mauritanian' },
    { emoji: '🇲🇸', name: 'flag montserrat ms montserratian' },
    { emoji: '🇲🇹', name: 'flag malta mt maltese' },
    { emoji: '🇲🇺', name: 'flag mauritius mu mauritian' },
    { emoji: '🇲🇻', name: 'flag maldives mv maldivian' },
    { emoji: '🇲🇼', name: 'flag malawi mw malawian' },
    { emoji: '🇲🇽', name: 'flag mexico mx mexican' },
    { emoji: '🇲🇾', name: 'flag malaysia my malaysian' },
    { emoji: '🇲🇿', name: 'flag mozambique mz mozambican' },
    { emoji: '🇳🇦', name: 'flag namibia na namibian' },
    { emoji: '🇳🇨', name: 'flag new caledonia nc new caledonian' },
    { emoji: '🇳🇪', name: 'flag niger ne nigerien' },
    { emoji: '🇳🇫', name: 'flag norfolk island nf' },
    { emoji: '🇳🇬', name: 'flag nigeria ng nigerian' },
    { emoji: '🇳🇮', name: 'flag nicaragua ni nicaraguan' },
    { emoji: '🇳🇱', name: 'flag netherlands nl dutch holland amsterdam' },
    { emoji: '🇳🇴', name: 'flag norway no norwegian oslo' },
    { emoji: '🇳🇵', name: 'flag nepal np nepali nepalese' },
    { emoji: '🇳🇷', name: 'flag nauru nr nauruan' },
    { emoji: '🇳🇺', name: 'flag niue nu niuean' },
    { emoji: '🇳🇿', name: 'flag new zealand nz kiwi new zealander aotearoa' },
    { emoji: '🇴🇲', name: 'flag oman om omani' },
    { emoji: '🇵🇦', name: 'flag panama pa panamanian' },
    { emoji: '🇵🇪', name: 'flag peru pe peruvian' },
    { emoji: '🇵🇫', name: 'flag french polynesia pf polynesian tahiti' },
    { emoji: '🇵🇬', name: 'flag papua new guinea pg papua new guinean papuan' },
    { emoji: '🇵🇭', name: 'flag philippines ph filipino pinoy pinay' },
    { emoji: '🇵🇰', name: 'flag pakistan pk pakistani' },
    { emoji: '🇵🇱', name: 'flag poland pl polish pole warsaw' },
    { emoji: '🇵🇲', name: 'flag st. pierre & miquelon pm saint pierre and miquelon' },
    { emoji: '🇵🇳', name: 'flag pitcairn islands pn pitcairn' },
    { emoji: '🇵🇷', name: 'flag puerto rico pr puerto rican' },
    { emoji: '🇵🇸', name: 'flag palestinian territories ps palestine palestinian' },
    { emoji: '🇵🇹', name: 'flag portugal pt portuguese lisbon' },
    { emoji: '🇵🇼', name: 'flag palau pw palauan' },
    { emoji: '🇵🇾', name: 'flag paraguay py paraguayan' },
    { emoji: '🇶🇦', name: 'flag qatar qa qatari' },
    { emoji: '🇷🇪', name: 'flag réunion re reunion reunionese' },
    { emoji: '🇷🇴', name: 'flag romania ro romanian' },
    { emoji: '🇷🇸', name: 'flag serbia rs serbian serb' },
    { emoji: '🇷🇺', name: 'flag russia ru russian federation moscow' },
    { emoji: '🇷🇼', name: 'flag rwanda rw rwandan' },
    { emoji: '🇸🇦', name: 'flag saudi arabia sa saudi arabian' },
    { emoji: '🇸🇧', name: 'flag solomon islands sb solomon islander' },
    { emoji: '🇸🇨', name: 'flag seychelles sc seychellois' },
    { emoji: '🇸🇩', name: 'flag sudan sd sudanese' },
    { emoji: '🇸🇪', name: 'flag sweden se swedish swede stockholm' },
    { emoji: '🇸🇬', name: 'flag singapore sg singaporean' },
    { emoji: '🇸🇭', name: 'flag st. helena sh saint helena' },
    { emoji: '🇸🇮', name: 'flag slovenia si slovenian slovene' },
    { emoji: '🇸🇯', name: 'flag svalbard & jan mayen sj' },
    { emoji: '🇸🇰', name: 'flag slovakia sk slovak' },
    { emoji: '🇸🇱', name: 'flag sierra leone sl sierra leonean' },
    { emoji: '🇸🇲', name: 'flag san marino sm sammarinese' },
    { emoji: '🇸🇳', name: 'flag senegal sn senegalese' },
    { emoji: '🇸🇴', name: 'flag somalia so somali' },
    { emoji: '🇸🇷', name: 'flag suriname sr surinamese' },
    { emoji: '🇸🇸', name: 'flag south sudan ss south sudanese' },
    { emoji: '🇸🇹', name: 'flag são tomé & príncipe st sao tome and principe santomean' },
    { emoji: '🇸🇻', name: 'flag el salvador sv salvadoran' },
    { emoji: '🇸🇽', name: 'flag sint maarten sx' },
    { emoji: '🇸🇾', name: 'flag syria sy syrian' },
    { emoji: '🇸🇿', name: 'flag eswatini sz swazi swaziland' },
    { emoji: '🇹🇦', name: 'flag tristan da cunha ta' },
    { emoji: '🇹🇨', name: 'flag turks & caicos islands tc' },
    { emoji: '🇹🇩', name: 'flag chad td chadian' },
    { emoji: '🇹🇫', name: 'flag french southern territories tf' },
    { emoji: '🇹🇬', name: 'flag togo tg togolese' },
    { emoji: '🇹🇭', name: 'flag thailand th thai' },
    { emoji: '🇹🇯', name: 'flag tajikistan tj tajik' },
    { emoji: '🇹🇰', name: 'flag tokelau tk' },
    { emoji: '🇹🇱', name: 'flag timor-leste tl east timor timorese' },
    { emoji: '🇹🇲', name: 'flag turkmenistan tm turkmen' },
    { emoji: '🇹🇳', name: 'flag tunisia tn tunisian' },
    { emoji: '🇹🇴', name: 'flag tonga to tongan' },
    { emoji: '🇹🇷', name: 'flag turkey tr turkish turk istanbul ankara' },
    { emoji: '🇹🇹', name: 'flag trinidad & tobago tt trinidadian tobagonian' },
    { emoji: '🇹🇻', name: 'flag tuvalu tv tuvaluan' },
    { emoji: '🇹🇼', name: 'flag taiwan tw taiwanese taipei' },
    { emoji: '🇹🇿', name: 'flag tanzania tz tanzanian' },
    { emoji: '🇺🇦', name: 'flag ukraine ua ukrainian kyiv' },
    { emoji: '🇺🇬', name: 'flag uganda ug ugandan' },
    { emoji: '🇺🇲', name: 'flag u.s. outlying islands um united states minor outlying islands' },
    { emoji: '🇺🇳', name: 'flag united nations un' },
    { emoji: '🇺🇸', name: 'flag united states us usa america american stars stripes washington dc' },
    { emoji: '🇺🇾', name: 'flag uruguay uy uruguayan' },
    { emoji: '🇺🇿', name: 'flag uzbekistan uz uzbek' },
    { emoji: '🇻🇦', name: 'flag vatican city va holy see' },
    { emoji: '🇻🇨', name: 'flag st. vincent & grenadines vc saint vincent and grenadines vincentian' },
    { emoji: '🇻🇪', name: 'flag venezuela ve venezuelan' },
    { emoji: '🇻🇬', name: 'flag british virgin islands vg' },
    { emoji: '🇻🇮', name: 'flag u.s. virgin islands vi united states virgin islands' },
    { emoji: '🇻🇳', name: 'flag vietnam vn vietnamese' },
    { emoji: '🇻🇺', name: 'flag vanuatu vu ni-vanuatu' },
    { emoji: '🇼🇫', name: 'flag wallis & futuna wf' },
    { emoji: '🇼🇸', name: 'flag samoa ws samoan' },
    { emoji: '🇽🇰', name: 'flag kosovo xk kosovar' },
    { emoji: '🇾🇪', name: 'flag yemen ye yemeni' },
    { emoji: '🇾🇹', name: 'flag mayotte yt' },
    { emoji: '🇿🇦', name: 'flag south africa za south african' },
    { emoji: '🇿🇲', name: 'flag zambia zm zambian' },
    { emoji: '🇿🇼', name: 'flag zimbabwe zw zimbabwean' },
    { emoji: '🏴󠁧󠁢󠁥󠁮󠁧󠁿', name: 'flag england english gb uk britain british england cross of st george' },
    { emoji: '🏴󠁧󠁢󠁳󠁣󠁴󠁿', name: 'flag scotland scottish gb uk britain british scot st andrew cross saltire' },
    { emoji: '🏴󠁧󠁢󠁷󠁬󠁳󠁿', name: 'flag wales welsh gb uk britain british cymru dragon' },

    // Money and Shopping
    { emoji: '₿', name: 'btc bitcoin money wealth rich' },
    { emoji: '💰', name: 'money bag cash dollar wealth rich' },
    { emoji: '💴', name: 'yen banknote money japan currency' },
    { emoji: '💵', name: 'dollar banknote money usa currency' },
    { emoji: '💶', name: 'euro banknote money europe currency' },
    { emoji: '💷', name: 'pound banknote money uk british currency' },
    { emoji: '💸', name: 'money with wings spending cash flying wealth' },
    { emoji: '💳', name: 'credit card money payment shopping debit' },
    { emoji: '🧾', name: 'receipt payment bill invoice' },
    { emoji: '💹', name: 'chart increasing with yen market growth stocks' },
    { emoji: '💱', name: 'currency exchange money forex' },
    { emoji: '💲', name: 'heavy dollar sign money currency cash' },
    { emoji: '✉️', name: 'envelope mail letter correspondence message' },
    { emoji: '📧', name: 'email message electronic communication' },
    { emoji: '📨', name: 'incoming envelope mail receive letter' },
    { emoji: '📩', name: 'envelope with arrow mail send message' },
    { emoji: '📤', name: 'outbox tray mail send' },
    { emoji: '📥', name: 'inbox tray mail receive' },
    { emoji: '📦', name: 'package delivery box shipping parcel' },
    { emoji: '📪', name: 'closed mailbox with lowered flag mail' },
    { emoji: '📫', name: 'closed mailbox with raised flag mail' },
    { emoji: '📬', name: 'open mailbox with raised flag mail' },
    { emoji: '📭', name: 'open mailbox with lowered flag mail' },
    { emoji: '📮', name: 'postbox mail letter send postal' },
    { emoji: '🛒', name: 'shopping cart trolley store supermarket' }
];

// Apply some runtime changes to our EmojiDEX
for (cEmoji of arrEmojis) {
    // Force everything in to lowercase
    cEmoji.name = cEmoji.name.toLowerCase();

    // Add our 'used' integer to track usage for personalised emoji lists
    cEmoji.used = 0;
}

/**
 * Search emojis with fuzzy matching for typos
 * @param {string} search - Search term
 */
function searchEmojis(search) {
    if (!search || search.length < 1) return [];
    
    search = search.toLowerCase();
    const results = [];
    
    for (const emojiData of arrEmojis) {
        const name = emojiData.name.toLowerCase();
        const words = name.split(' ');
        
        let bestMatch = null;
        
        for (const word of words) {
            // Exact match - highest priority
            if (word === search) {
                bestMatch = { score: 0, word };
                break;
            }
            
            // Word starts with search
            if (word.startsWith(search) && search.length >= 2) {
                const score = 0.1;
                if (!bestMatch || score < bestMatch.score) {
                    bestMatch = { score, word };
                }
            }
            
            // Fuzzy matching for 3+ character searches
            if (search.length >= 3) {
                const lengthDiff = Math.abs(word.length - search.length);
                
                // Check words with similar length
                if (lengthDiff <= 1) {
                    const distance = levenshteinDistance(word, search);
                    
                    if (distance === 1) {
                        // Verify sufficient character overlap
                        const searchChars = new Set(search);
                        const wordChars = new Set(word);
                        const commonChars = [...searchChars].filter(c => wordChars.has(c)).length;
                        
                        if (commonChars >= search.length - 1) {
                            let score = 0.5;
                            
                            // Better score for missing letter at end (hart → heart)
                            if (word.length > search.length && word.startsWith(search)) {
                                score = 0.3;
                            }
                            // Better score for missing letter in middle
                            else if (word.length > search.length && 
                                     word[0] === search[0] && 
                                     word[word.length-1] === search[search.length-1]) {
                                score = 0.35;
                            }
                            
                            if (!bestMatch || score < bestMatch.score) {
                                bestMatch = { score, word };
                            }
                        }
                    }
                }
                
                // Check if search matches beginning of longer words
                if (word.length > search.length && lengthDiff <= 3) {
                    const wordStart = word.substring(0, search.length);
                    const distance = levenshteinDistance(wordStart, search);
                    
                    if (distance === 1) {
                        const score = 0.6;
                        if (!bestMatch || score < bestMatch.score) {
                            bestMatch = { score, word };
                        }
                    }
                }
            }
            
            // For 5+ character searches, allow distance 2
            if (search.length >= 5) {
                const distance = levenshteinDistance(word, search);
                if (distance === 2 && Math.abs(word.length - search.length) <= 1) {
                    const score = 0.8;
                    if (!bestMatch || score < bestMatch.score) {
                        bestMatch = { score, word };
                    }
                }
            }
        }
        
        if (bestMatch) {
            results.push({
                ...emojiData,
                score: bestMatch.score,
                matchedWord: bestMatch.word
            });
        }
    }
    
    // If no results found, fall back to includes search
    if (results.length === 0) {
        for (const emojiData of arrEmojis) {
            const name = emojiData.name.toLowerCase();
            if (name.includes(search)) {
                results.push({
                    ...emojiData,
                    score: 1.0, // Lower priority than fuzzy matches
                    matchedWord: name
                });
            }
        }
    }
    
    // Sort by relevance
    return results
        .sort((a, b) => {
            if (Math.abs(a.score - b.score) > 0.01) return a.score - b.score;
            
            // For same scores, prefer shorter matched words
            const aLen = a.matchedWord.length;
            const bLen = b.matchedWord.length;
            if (aLen !== bLen) return aLen - bLen;
            
            return a.matchedWord.localeCompare(b.matchedWord);
        })
        .map(({ score, matchedWord, ...emoji }) => emoji);
}

/** Return our most used emojis */
function getMostUsedEmojis() {
    return arrEmojis.sort((a, b) => b.used - a.used);
}

/**
 * Checks if the given string consists only of emojis, ignoring whitespace.
 * 
 * @param {string} str - The string to check for emojis.
 * @returns {boolean} True if the string contains only emojis (ignoring whitespace), false otherwise.
 */
function isEmojiOnly(str) {
    // Remove all whitespace from the string
    const strWithoutSpace = str.replace(/\s/g, '');
    
    // If the string is empty after removing whitespace, return false
    if (strWithoutSpace.length === 0) return false;
    
    // Use Intl.Segmenter to properly split the string into graphemes (including emoji sequences)
    const segmenter = new Intl.Segmenter(undefined, { granularity: 'grapheme' });
    const segments = [...segmenter.segment(strWithoutSpace)].map(s => s.segment);
    
    // Check if each segment is an emoji using a test for emoji presentation
    return segments.every(segment => {
        // Test for emoji property
        return /\p{Emoji_Presentation}/u.test(segment) || 
               // Handle basic emojis that need variation selectors
               (/\p{Emoji}/u.test(segment) && 
                !/\p{Number}|\p{Letter}/u.test(segment));
    });
}

/**
 * Converts an ISO 3166-1 alpha-2 country code to its corresponding flag emoji.
 * @param {string} isoCode - The two-letter ISO country code
 * @returns {string} The flag emoji or a globe emoji if invalid
 */
function isoToFlagEmoji(isoCode) {
    if (!isoCode || isoCode.length !== 2) return '🌍';
    
    const upperIso = isoCode.toUpperCase();
    const codePointA = upperIso.charCodeAt(0) - 65 + 0x1F1E6;
    const codePointB = upperIso.charCodeAt(1) - 65 + 0x1F1E6;
    
    return String.fromCodePoint(codePointA, codePointB);
}

/**
 * Convert all Unicode emojis in the given DOM element to Twemoji SVGs
 * @param {HTMLElement} domElement 
 */
function twemojify(domElement) {
    twemoji.parse(domElement, { callback: (icon, _) => '/twemoji/svg/' + icon + '.svg' });
}