/** A custom-built, probably inefficient, emoji dataset and utility set */

const arrEmojis = [
    // People
    { emoji: '😀', name: 'grinning face', used: 0 },
    { emoji: '😃', name: 'grinning face with big eyes', used: 0 },
    { emoji: '😄', name: 'smile', used: 0 },
    { emoji: '😁', name: 'grinning face with smiling eyes', used: 0 },
    { emoji: '😆', name: 'grin squinting face', used: 0 },
    { emoji: '😅', name: 'nervous face with sweat', used: 0 },
    { emoji: '🤣', name: 'rofl lmao', used: 0 },
    { emoji: '😂', name: 'joy laugh lol', used: 0 },
    { emoji: '🙂', name: 'slightly smiling face', used: 0 },
    { emoji: '🙃', name: 'upside-down face', used: 0 },
    { emoji: '😉', name: 'winking face', used: 0 },
    { emoji: '😊', name: 'smiling face with smiling eyes', used: 0 },
    { emoji: '😇', name: 'smiling face with halo', used: 0 },
    { emoji: '🥰', name: 'smiling face with hearts', used: 0 },
    { emoji: '😍', name: 'smiling face with heart eyes', used: 0 },
    { emoji: '🤩', name: 'star-struck', used: 0 },
    { emoji: '😘', name: 'face blowing a kiss', used: 0 },
    { emoji: '😗', name: 'kissing face', used: 0 },
    { emoji: '😚', name: 'kissing face with closed eyes', used: 0 },
    { emoji: '😙', name: 'kissing face with smiling eyes', used: 0 },
    { emoji: '😋', name: 'face savoring food', used: 0 },
    { emoji: '😛', name: 'face with tongue', used: 0 },
    { emoji: '😜', name: 'winking face with tongue', used: 0 },
    { emoji: '🤪', name: 'zany face', used: 0 },
    { emoji: '😝', name: 'squinting face with tongue', used: 0 },
    { emoji: '🤑', name: 'money-mouth face', used: 0 },
    { emoji: '🤗', name: 'hugging face', used: 0 },
    { emoji: '🤭', name: 'face with hand over mouth', used: 0 },
    { emoji: '🤫', name: 'shushing face', used: 0 },
    { emoji: '🤔', name: 'thinking face', used: 0 },
    { emoji: '🤐', name: 'zipper-mouth face', used: 0 },
    { emoji: '🤨', name: 'face with raised eyebrow', used: 0 },
    { emoji: '😐', name: 'neutral face', used: 0 },
    { emoji: '😑', name: 'expressionless face', used: 0 },
    { emoji: '😶', name: 'face without mouth', used: 0 },
    { emoji: '😏', name: 'smirking face', used: 0 },
    { emoji: '😒', name: 'unamused face', used: 0 },
    { emoji: '🙄', name: 'face with rolling eyes', used: 0 },
    { emoji: '😬', name: 'grimacing face', used: 0 },
    { emoji: '🤥', name: 'lying face', used: 0 },
    { emoji: '😌', name: 'relieved face', used: 0 },
    { emoji: '😔', name: 'pensive face', used: 0 },
    { emoji: '😪', name: 'sleepy face', used: 0 },
    { emoji: '🤤', name: 'drooling face', used: 0 },
    { emoji: '😴', name: 'sleeping face', used: 0 },
    { emoji: '😷', name: 'face with medical mask', used: 0 },
    { emoji: '🤒', name: 'face with thermometer', used: 0 },
    { emoji: '🤕', name: 'face with head-bandage', used: 0 },
    { emoji: '🤢', name: 'nauseated face', used: 0 },
    { emoji: '🤮', name: 'face vomiting', used: 0 },
    { emoji: '🤧', name: 'sneezing face', used: 0 },
    { emoji: '🥵', name: 'hot face', used: 0 },
    { emoji: '🥶', name: 'cold face', used: 0 },
    { emoji: '🥴', name: 'woozy face', used: 0 },
    { emoji: '😵', name: 'dizzy face', used: 0 },
    { emoji: '😵‍💫', name: 'face with spiral eyes', used: 0 },
    { emoji: '🤯', name: 'exploding head', used: 0 },
    { emoji: '🤠', name: 'cowboy hat face', used: 0 },
    { emoji: '🥳', name: 'partying face', used: 0 },
    { emoji: '😎', name: 'smiling face with sunglasses', used: 0 },
    { emoji: '🤓', name: 'nerd face', used: 0 },
    { emoji: '🧐', name: 'face with monocle', used: 0 },
    { emoji: '😕', name: 'confused face', used: 0 },
    { emoji: '😟', name: 'worried face', used: 0 },
    { emoji: '🙁', name: 'slightly frowning face', used: 0 },
    { emoji: '☹️', name: 'frowning face', used: 0 },
    { emoji: '😮', name: 'face with open mouth', used: 0 },
    { emoji: '😯', name: 'hushed face', used: 0 },
    { emoji: '😲', name: 'astonished face', used: 0 },
    { emoji: '😳', name: 'flushed face', used: 0 },
    { emoji: '🥺', name: 'pleading face', used: 0 },
    { emoji: '😦', name: 'frowning face with open mouth', used: 0 },
    { emoji: '😧', name: 'anguished face', used: 0 },
    { emoji: '😨', name: 'fearful face', used: 0 },
    { emoji: '😰', name: 'anxious face with sweat', used: 0 },
    { emoji: '😥', name: 'sad but relieved face', used: 0 },
    { emoji: '😢', name: 'crying face', used: 0 },
    { emoji: '😭', name: 'loudly crying face', used: 0 },
    { emoji: '😱', name: 'face screaming in fear', used: 0 },
    { emoji: '😖', name: 'confounded face', used: 0 },
    { emoji: '😣', name: 'persevering face', used: 0 },
    { emoji: '😞', name: 'disappointed face', used: 0 },
    { emoji: '😓', name: 'downcast face with sweat', used: 0 },
    { emoji: '😩', name: 'weary face', used: 0 },
    { emoji: '😫', name: 'tired face', used: 0 },
    { emoji: '🥱', name: 'yawning face', used: 0 },
    { emoji: '✨', name: 'sparkles', used: 0 },
    { emoji: '🌟', name: 'glowing star', used: 0 },
    { emoji: '⭐', name: 'white medium star', used: 0 },
    { emoji: '🌠', name: 'shooting star', used: 0 },
    { emoji: '☄️', name: 'comet', used: 0 },
    { emoji: '🔥', name: 'fire', used: 0 },
    { emoji: '💧', name: 'droplet', used: 0 },
    { emoji: '🌈', name: 'rainbow', used: 0 },
    { emoji: '❄️', name: 'snowflake', used: 0 },
    { emoji: '☃️', name: 'snowman', used: 0 },
    { emoji: '⛄', name: 'snowman without snow', used: 0 },
    { emoji: '🌞', name: 'sun with face', used: 0 },
    { emoji: '🌝', name: 'full moon with face', used: 0 },
    { emoji: '🌜', name: 'last quarter moon with face', used: 0 },
    { emoji: '🌛', name: 'first quarter moon with face', used: 0 },
    { emoji: '🌚', name: 'new moon with face', used: 0 },
    { emoji: '🌕', name: 'full moon', used: 0 },
    { emoji: '🌖', name: 'waning gibbous moon', used: 0 },
    { emoji: '🌗', name: 'last quarter moon', used: 0 },
    { emoji: '🌘', name: 'waning crescent moon', used: 0 },
    { emoji: '🌑', name: 'new moon', used: 0 },
    { emoji: '🌒', name: 'waxing crescent moon', used: 0 },
    { emoji: '🌓', name: 'first quarter moon', used: 0 },
    { emoji: '🌔', name: 'waxing gibbous moon', used: 0 },
    { emoji: '🌙', name: 'crescent moon', used: 0 },
    { emoji: '🌌', name: 'milky way', used: 0 },
    { emoji: '🌍', name: 'globe showing Europe-Africa', used: 0 },
    { emoji: '🌎', name: 'globe showing Americas', used: 0 },
    { emoji: '🌏', name: 'globe showing Asia-Australia', used: 0 },
    { emoji: '🌐', name: 'globe with meridians', used: 0 },
    { emoji: '🪐', name: 'ringed planet', used: 0 },
    { emoji: '🛸', name: 'flying saucer', used: 0 },
    { emoji: '🌊', name: 'water wave', used: 0 },

    // Food
    { emoji: '🍏', name: 'green apple', used: 0 },
    { emoji: '🍎', name: 'red apple', used: 0 },
    { emoji: '🍐', name: 'pear', used: 0 },
    { emoji: '🍊', name: 'tangerine', used: 0 },
    { emoji: '🍋', name: 'lemon', used: 0 },
    { emoji: '🍌', name: 'banana', used: 0 },
    { emoji: '🍉', name: 'watermelon', used: 0 },
    { emoji: '🍇', name: 'grapes', used: 0 },
    { emoji: '🍓', name: 'strawberry', used: 0 },
    { emoji: '🍈', name: 'melon', used: 0 },
    { emoji: '🍒', name: 'cherries', used: 0 },
    { emoji: '🍑', name: 'peach', used: 0 },
    { emoji: '🥭', name: 'mango', used: 0 },
    { emoji: '🍍', name: 'pineapple', used: 0 },
    { emoji: '🥥', name: 'coconut', used: 0 },
    { emoji: '🥝', name: 'kiwi fruit', used: 0 },
    { emoji: '🍅', name: 'tomato', used: 0 },
    { emoji: '🥑', name: 'avocado', used: 0 },
    { emoji: '🍆', name: 'eggplant', used: 0 },
    { emoji: '🥔', name: 'potato', used: 0 },
    { emoji: '🥕', name: 'carrot', used: 0 },
    { emoji: '🌽', name: 'ear of corn', used: 0 },
    { emoji: '🌶️', name: 'hot pepper', used: 0 },
    { emoji: '🥒', name: 'cucumber', used: 0 },
    { emoji: '🥬', name: 'leafy green', used: 0 },
    { emoji: '🥦', name: 'broccoli', used: 0 },
    { emoji: '🧄', name: 'garlic', used: 0 },
    { emoji: '🧅', name: 'onion', used: 0 },
    { emoji: '🍄', name: 'mushroom', used: 0 },
    { emoji: '🥜', name: 'peanuts', used: 0 },
    { emoji: '🌰', name: 'chestnut', used: 0 },
    { emoji: '🍞', name: 'bread', used: 0 },
    { emoji: '🥐', name: 'croissant', used: 0 },
    { emoji: '🥖', name: 'baguette bread', used: 0 },
    { emoji: '🥨', name: 'pretzel', used: 0 },
    { emoji: '🥯', name: 'bagel', used: 0 },
    { emoji: '🥞', name: 'pancakes', used: 0 },
    { emoji: '🧇', name: 'waffle', used: 0 },
    { emoji: '🧀', name: 'cheese wedge', used: 0 },
    { emoji: '🍳', name: 'cooking', used: 0 },
    { emoji: '🍲', name: 'pot of food', used: 0 },
    { emoji: '🥣', name: 'bowl with spoon', used: 0 },
    { emoji: '🥗', name: 'green salad', used: 0 },
    { emoji: '🍿', name: 'popcorn', used: 0 },
    { emoji: '🧈', name: 'butter', used: 0 },
    { emoji: '🍗', name: 'poultry leg', used: 0 },
    { emoji: '🍖', name: 'meat on bone', used: 0 },
    { emoji: '🥩', name: 'cut of meat', used: 0 },
    { emoji: '🍤', name: 'fried shrimp', used: 0 },
    { emoji: '🍚', name: 'cooked rice', used: 0 },
    { emoji: '🍛', name: 'curry rice', used: 0 },
    { emoji: '🍜', name: 'steaming bowl', used: 0 },
    { emoji: '🍝', name: 'spaghetti', used: 0 },
    { emoji: '🍠', name: 'roasted sweet potato', used: 0 },
    { emoji: '🍢', name: 'oden', used: 0 },
    { emoji: '🍣', name: 'sushi', used: 0 },
    { emoji: '🍱', name: 'bento box', used: 0 },
    { emoji: '🥟', name: 'dumpling', used: 0 },
    { emoji: '🍘', name: 'rice cracker', used: 0 },
    { emoji: '🍙', name: 'rice ball', used: 0 },
    { emoji: '🍚', name: 'cooked rice', used: 0 },
    { emoji: '🍡', name: 'dango', used: 0 },
    { emoji: '🥮', name: 'moon cake', used: 0 },
    { emoji: '🍧', name: 'shaved ice', used: 0 },
    { emoji: '🍨', name: 'ice cream', used: 0 },
    { emoji: '🍦', name: 'soft ice cream', used: 0 },
    { emoji: '🥧', name: 'pie', used: 0 },
    { emoji: '🍰', name: 'shortcake', used: 0 },
    { emoji: '🎂', name: 'birthday cake', used: 0 },
    { emoji: '🍮', name: 'custard', used: 0 },
    { emoji: '🍭', name: 'lollipop', used: 0 },
    { emoji: '🍬', name: 'candy', used: 0 },
    { emoji: '🍫', name: 'chocolate bar', used: 0 },
    { emoji: '🍿', name: 'popcorn', used: 0 },
    { emoji: '🍩', name: 'doughnut', used: 0 },
    { emoji: '🍪', name: 'cookie', used: 0 },
    { emoji: '🥛', name: 'glass of milk', used: 0 },
    { emoji: '🍺', name: 'beer mug', used: 0 },
    { emoji: '🍻', name: 'clinking beer mugs', used: 0 },
    { emoji: '🥂', name: 'clinking glasses', used: 0 },
    { emoji: '🍷', name: 'wine glass', used: 0 },
    { emoji: '🥃', name: 'tumbler glass', used: 0 },
    { emoji: '🍸', name: 'cocktail glass', used: 0 },
    { emoji: '🍹', name: 'tropical drink', used: 0 },
    { emoji: '🍾', name: 'bottle with popping cork', used: 0 },
    { emoji: '🥤', name: 'cup with straw', used: 0 },
    { emoji: '🧃', name: 'beverage box', used: 0 },
    { emoji: '🧉', name: 'mate', used: 0 },
    { emoji: '🧊', name: 'ice cube', used: 0 },

    // Animals
    { emoji: '🐨', name: 'koala', used: 0 },
    { emoji: '🦥', name: 'sloth', used: 0 },
    { emoji: '🦦', name: 'otter', used: 0 },
    { emoji: '🦨', name: 'skunk', used: 0 },
    { emoji: '🦩', name: 'flamingo', used: 0 },
    { emoji: '🐦', name: 'bird', used: 0 },
    { emoji: '🦜', name: 'parrot', used: 0 },
    { emoji: '🦢', name: 'swan', used: 0 },
    { emoji: '🦅', name: 'eagle', used: 0 },
    { emoji: '🐧', name: 'penguin', used: 0 },
    { emoji: '🕊️', name: 'dove', used: 0 },
    { emoji: '🦉', name: 'owl', used: 0 },
    { emoji: '🦚', name: 'peacock', used: 0 },
    { emoji: '🦜', name: 'parrot', used: 0 },
    { emoji: '🦢', name: 'swan', used: 0 },
    { emoji: '🐤', name: 'baby chick', used: 0 },
    { emoji: '🐥', name: 'front-facing baby chick', used: 0 },
    { emoji: '🐣', name: 'hatching chick', used: 0 },
    { emoji: '🐺', name: 'wolf face', used: 0 },
    { emoji: '🦝', name: 'raccoon', used: 0 },
    { emoji: '🐗', name: 'boar', used: 0 },
    { emoji: '🐴', name: 'horse face', used: 0 },
    { emoji: '🦄', name: 'unicorn face', used: 0 },
    { emoji: '🐎', name: 'horse', used: 0 },
    { emoji: '🦓', name: 'zebra', used: 0 },
    { emoji: '🦒', name: 'giraffe', used: 0 },
    { emoji: '🐪', name: 'camel', used: 0 },
    { emoji: '🐫', name: 'two-hump camel', used: 0 },
    { emoji: '🦙', name: 'llama', used: 0 },
    { emoji: '🦘', name: 'kangaroo', used: 0 },
    { emoji: '🐂', name: 'ox', used: 0 },
    { emoji: '🐃', name: 'water buffalo', used: 0 },
    { emoji: '🐄', name: 'cow', used: 0 },
    { emoji: '🐑', name: 'sheep', used: 0 },
    { emoji: '🐐', name: 'goat', used: 0 },
    { emoji: '🐏', name: 'ram', used: 0 },
    { emoji: '🐖', name: 'pig', used: 0 },
    { emoji: '🐗', name: 'boar', used: 0 },
    { emoji: '🐕', name: 'dog', used: 0 },
    { emoji: '🐩', name: 'poodle', used: 0 },
    { emoji: '🐈', name: 'cat', used: 0 },
    { emoji: '🐱', name: 'cat face', used: 0 },
    { emoji: '🦇', name: 'bat', used: 0 },
    { emoji: '🐀', name: 'rat', used: 0 },
    { emoji: '🐁', name: 'mouse', used: 0 },
    { emoji: '🦔', name: 'hedgehog', used: 0 },
    { emoji: '🦡', name: 'badger', used: 0 },
    { emoji: '🐿️', name: 'chipmunk', used: 0 },
    { emoji: '🐾', name: 'paw prints', used: 0 },
    { emoji: '🦀', name: 'crab', used: 0 },
    { emoji: '🦞', name: 'lobster', used: 0 },
    { emoji: '🦐', name: 'shrimp', used: 0 },
    { emoji: '🦑', name: 'squid', used: 0 },
    { emoji: '🐙', name: 'octopus', used: 0 },
    { emoji: '🦪', name: 'oyster', used: 0 },
    { emoji: '🐠', name: 'tropical fish', used: 0 },
    { emoji: '🐟', name: 'fish', used: 0 },
    { emoji: '🐡', name: 'blowfish', used: 0 },
    { emoji: '🐬', name: 'dolphin', used: 0 },
    { emoji: '🐳', name: 'spouting whale', used: 0 },
    { emoji: '🐋', name: 'whale', used: 0 },
    { emoji: '🦈', name: 'shark', used: 0 },
    { emoji: '🐊', name: 'crocodile', used: 0 },
    { emoji: '🐢', name: 'turtle', used: 0 },
    { emoji: '🦎', name: 'lizard', used: 0 },
    { emoji: '🐍', name: 'snake', used: 0 },
    { emoji: '🐉', name: 'dragon', used: 0 },
    { emoji: '🦕', name: 'sauropod', used: 0 },
    { emoji: '🦖', name: 'T-Rex', used: 0 },
    { emoji: '🐲', name: 'dragon face', used: 0 },
    { emoji: '🦂', name: 'scorpion', used: 0 },
    { emoji: '🕷️', name: 'spider', used: 0 },
    { emoji: '🕸️', name: 'spider web', used: 0 },
    { emoji: '🐜', name: 'ant', used: 0 },
    { emoji: '🐝', name: 'honeybee', used: 0 },
    { emoji: '🐞', name: 'lady beetle', used: 0 },
    { emoji: '🦗', name: 'cricket', used: 0 },
    { emoji: '🪳', name: 'cockroach', used: 0 },
    { emoji: '🐌', name: 'snail', used: 0 },
    { emoji: '🦋', name: 'butterfly', used: 0 },
    { emoji: '🐛', name: 'bug', used: 0 },

    // Items
    { emoji: '🎒', name: 'backpack', used: 0 },
    { emoji: '👓', name: 'glasses', used: 0 },
    { emoji: '🕶️', name: 'sunglasses', used: 0 },
    { emoji: '🌂', name: 'closed umbrella', used: 0 },
    { emoji: '🧳', name: 'luggage', used: 0 },
    { emoji: '👜', name: 'handbag', used: 0 },
    { emoji: '👛', name: 'purse', used: 0 },
    { emoji: '👝', name: 'pouch', used: 0 },
    { emoji: '🎽', name: 'running shirt', used: 0 },
    { emoji: '👕', name: 't-shirt', used: 0 },
    { emoji: '👖', name: 'jeans', used: 0 },
    { emoji: '🧣', name: 'scarf', used: 0 },
    { emoji: '🧤', name: 'gloves', used: 0 },
    { emoji: '🧥', name: 'coat', used: 0 },
    { emoji: '🧦', name: 'socks', used: 0 },
    { emoji: '👗', name: 'dress', used: 0 },
    { emoji: '👙', name: 'bikini', used: 0 },
    { emoji: '👘', name: 'kimono', used: 0 },
    { emoji: '👠', name: 'high-heeled shoe', used: 0 },
    { emoji: '👡', name: 'sandal', used: 0 },
    { emoji: '👢', name: 'woman’s boot', used: 0 },
    { emoji: '👞', name: 'man’s shoe', used: 0 },
    { emoji: '👟', name: 'running shoe', used: 0 },
    { emoji: '👒', name: 'woman’s hat', used: 0 },
    { emoji: '🎩', name: 'top hat', used: 0 },
    { emoji: '🎓', name: 'graduation cap', used: 0 },
    { emoji: '🧢', name: 'billed cap', used: 0 },
    { emoji: '⛑️', name: 'rescue worker’s helmet', used: 0 },
    { emoji: '💼', name: 'briefcase', used: 0 },
    { emoji: '📱', name: 'mobile phone', used: 0 },
    { emoji: '📲', name: 'mobile phone with arrow', used: 0 },
    { emoji: '☎️', name: 'telephone', used: 0 },
    { emoji: '📞', name: 'telephone receiver', used: 0 },
    { emoji: '📟', name: 'pager', used: 0 },
    { emoji: '📠', name: 'fax machine', used: 0 },
    { emoji: '🔋', name: 'battery', used: 0 },
    { emoji: '🔌', name: 'electric plug', used: 0 },
    { emoji: '💡', name: 'light bulb', used: 0 },
    { emoji: '🔦', name: 'flashlight', used: 0 },
    { emoji: '🕯️', name: 'candle', used: 0 },
    { emoji: '🪔', name: 'diya lamp', used: 0 },
    { emoji: '💣', name: 'bomb', used: 0 },
    { emoji: '🧨', name: 'firecracker', used: 0 },
    { emoji: '🔫', name: 'pistol', used: 0 },
    { emoji: '🧰', name: 'toolbox', used: 0 },
    { emoji: '🪛', name: 'screwdriver', used: 0 },
    { emoji: '🔧', name: 'wrench', used: 0 },
    { emoji: '🔨', name: 'hammer', used: 0 },
    { emoji: '⛏️', name: 'pick', used: 0 },
    { emoji: '🪓', name: 'axe', used: 0 },
    { emoji: '🔩', name: 'nut and bolt', used: 0 },
    { emoji: '⚙️', name: 'gear', used: 0 },
    { emoji: '🧱', name: 'brick', used: 0 },
    { emoji: '🪝', name: 'hook', used: 0 },
    { emoji: '🧲', name: 'magnet', used: 0 },
    { emoji: '🔗', name: 'link', used: 0 },
    { emoji: '🧷', name: 'safety pin', used: 0 },
    { emoji: '🧴', name: 'lotion bottle', used: 0 },
    { emoji: '🧵', name: 'thread', used: 0 },
    { emoji: '🧶', name: 'yarn', used: 0 },
    { emoji: '🪡', name: 'sewing needle', used: 0 },
    { emoji: '📌', name: 'pushpin', used: 0 },
    { emoji: '📍', name: 'round pushpin', used: 0 },
    { emoji: '📎', name: 'paperclip', used: 0 },
    { emoji: '🖇️', name: 'linked paperclips', used: 0 },
    { emoji: '✂️', name: 'scissors', used: 0 },
    { emoji: '🧹', name: 'broom', used: 0 },
    { emoji: '🧺', name: 'basket', used: 0 },
    { emoji: '🧼', name: 'soap', used: 0 },
    { emoji: '🪠', name: 'plunger', used: 0 },
    { emoji: '🪣', name: 'bucket', used: 0 },
    { emoji: '🧽', name: 'sponge', used: 0 },
    { emoji: '🪤', name: 'mouse trap', used: 0 },

    // Hearts
    { emoji: '❤️', name: 'red heart', used: 0 },
    { emoji: '🧡', name: 'orange heart', used: 0 },
    { emoji: '💛', name: 'yellow heart', used: 0 },
    { emoji: '💚', name: 'green heart', used: 0 },
    { emoji: '💙', name: 'blue heart', used: 0 },
    { emoji: '💜', name: 'purple heart', used: 0 },
    { emoji: '🤎', name: 'brown heart', used: 0 },
    { emoji: '🖤', name: 'black heart', used: 0 },
    { emoji: '🤍', name: 'white heart', used: 0 },
    { emoji: '💕', name: 'two hearts', used: 0 },
    { emoji: '💞', name: 'revolving hearts', used: 0 },
    { emoji: '💓', name: 'beating heart', used: 0 },
    { emoji: '💗', name: 'growing heart', used: 0 },
    { emoji: '💖', name: 'sparkling heart', used: 0 },
    { emoji: '💘', name: 'heart with arrow', used: 0 },
    { emoji: '💝', name: 'heart with ribbon', used: 0 },
    { emoji: '💟', name: 'heart decoration', used: 0 },
    { emoji: '❣️', name: 'heart exclamation', used: 0 },
    { emoji: '💔', name: 'broken heart', used: 0 },
    { emoji: '❤️‍🔥', name: 'heart on fire', used: 0 },
    { emoji: '❤️‍🩹', name: 'mending heart', used: 0 },

    // Symbols
    { emoji: '✨', name: 'sparkles', used: 0 },
    { emoji: '🌟', name: 'glowing star', used: 0 },
    { emoji: '⭐', name: 'star', used: 0 },
    { emoji: '💫', name: 'dizzy star', used: 0 },
    { emoji: '🔥', name: 'fire', used: 0 },
    { emoji: '☄️', name: 'comet', used: 0 },
    { emoji: '💥', name: 'collision', used: 0 },
    { emoji: '💢', name: 'anger mad symbol', used: 0 },
    { emoji: '💬', name: 'speech balloon', used: 0 },
    { emoji: '👁️‍🗨️', name: 'eye in speech bubble', used: 0 },
    { emoji: '🗯️', name: 'right anger bubble', used: 0 },
    { emoji: '💭', name: 'thought balloon', used: 0 },
    { emoji: '🗨️', name: 'left speech bubble', used: 0 },
    { emoji: '🔯', name: 'dotted six-pointed star', used: 0 },
    { emoji: '✡️', name: 'star of david', used: 0 },
    { emoji: '✝️', name: 'latin cross', used: 0 },
    { emoji: '☪️', name: 'star and crescent', used: 0 },
    { emoji: '🕉️', name: 'om', used: 0 },
    { emoji: '☸️', name: 'wheel of dharma', used: 0 },
    { emoji: '✌️', name: 'victory hand', used: 0 },
    { emoji: '🖕', name: 'middle finger fuck you', used: 0 },
    { emoji: '🤞', name: 'crossed fingers', used: 0 },
    { emoji: '🖖', name: 'vulcan salute', used: 0 },
    { emoji: '✊', name: 'raised fist', used: 0 },
    { emoji: '👊', name: 'oncoming fist', used: 0 },
    { emoji: '🤛', name: 'left-facing fist', used: 0 },
    { emoji: '🤜', name: 'right-facing fist', used: 0 },
    { emoji: '👌', name: 'ok hand', used: 0 },
    { emoji: '🤌', name: 'pinched fingers', used: 0 },
    { emoji: '🤏', name: 'pinching hand', used: 0 },
    { emoji: '✋', name: 'raised hand', used: 0 },
    { emoji: '🖐️', name: 'hand with fingers splayed', used: 0 },
    { emoji: '🖖', name: 'vulcan salute', used: 0 },
    { emoji: '👋', name: 'waving hand', used: 0 },
    { emoji: '🤚', name: 'raised back of hand', used: 0 },
    { emoji: '🦿', name: 'mechanical leg', used: 0 },
    { emoji: '🦾', name: 'mechanical arm', used: 0 },
    { emoji: '🦻', name: 'ear with hearing aid', used: 0 },
    { emoji: '💅', name: 'nail polish', used: 0 },
    { emoji: '💪', name: 'flexed biceps', used: 0 },
    { emoji: '✍️', name: 'writing hand', used: 0 },
    { emoji: '🙏', name: 'folded hands', used: 0 },
    { emoji: '👐', name: 'open hands', used: 0 },
    { emoji: '🙌', name: 'raising hands', used: 0 },
    { emoji: '🤲', name: 'palms up together', used: 0 },
    { emoji: '🤝', name: 'handshake', used: 0 },
    { emoji: '🧠', name: 'brain', used: 0 },
    { emoji: '💡', name: 'light bulb', used: 0 },
    { emoji: '🔔', name: 'bell', used: 0 },
    { emoji: '🔕', name: 'bell with slash', used: 0 },
    { emoji: '🎵', name: 'musical note', used: 0 },
    { emoji: '🎶', name: 'musical notes', used: 0 },
    { emoji: '🔊', name: 'speaker high volume', used: 0 },
    { emoji: '🔇', name: 'muted speaker', used: 0 },

    // Weather and Nature
    { emoji: '☀️', name: 'sun', used: 0 },
    { emoji: '☔', name: 'umbrella with rain drops', used: 0 },
    { emoji: '🌬️', name: 'wind face', used: 0 },
    { emoji: '🌪️', name: 'tornado', used: 0 },
    { emoji: '🌫️', name: 'fog', used: 0 },
    { emoji: '🪨', name: 'rock', used: 0 },

    // Time and Calendar
    { emoji: '📅', name: 'calendar', used: 0 },
    { emoji: '🕰️', name: 'mantelpiece clock', used: 0 },
    { emoji: '⏰', name: 'alarm clock', used: 0 },
    { emoji: '⏳', name: 'hourglass not done', used: 0 },
    { emoji: '⌛', name: 'hourglass done', used: 0 },

    // Transportation
    { emoji: '🚗', name: 'car', used: 0 },
    { emoji: '🚕', name: 'taxi cab', used: 0 },
    { emoji: '🚲', name: 'bicycle bike', used: 0 },
    { emoji: '✈️', name: 'airplane', used: 0 },
    { emoji: '🚀', name: 'rocket', used: 0 },
    { emoji: '🚂', name: 'locomotive train', used: 0 },
    { emoji: '🛵', name: 'motor scooter', used: 0 },
    { emoji: '🛺', name: 'auto rickshaw', used: 0 },

    // Sports and Activities
    { emoji: '⚽', name: 'soccer ball', used: 0 },
    { emoji: '🏀', name: 'basketball', used: 0 },
    { emoji: '🏈', name: 'american football', used: 0 },
    { emoji: '⚾', name: 'baseball', used: 0 },
    { emoji: '🎾', name: 'tennis ball', used: 0 },
    { emoji: '🏒', name: 'ice hockey stick and puck', used: 0 },
    { emoji: '🏹', name: 'bow and arrow', used: 0 },
    { emoji: '⛸️', name: 'ice skate', used: 0 },
    { emoji: '🏊', name: 'swimmer', used: 0 },
    { emoji: '🧘', name: 'person in lotus position', used: 0 },

    // Miscellaneous Symbols
    { emoji: '♻️', name: 'recycling symbol', used: 0 },
    { emoji: '⚠️', name: 'warning', used: 0 },
    { emoji: '🚫', name: 'prohibited', used: 0 },
    { emoji: '🔞', name: 'no one under eighteen', used: 0 },
    { emoji: '🆗', name: 'ok button', used: 0 },
    { emoji: '🔙', name: 'back arrow', used: 0 },
    { emoji: '🔜', name: 'soon arrow', used: 0 },
    { emoji: '🔝', name: 'top arrow', used: 0 },
    { emoji: '💯', name: 'hundred points', used: 0 },
    { emoji: '🔄', name: 'counterclockwise arrows button' },
    { emoji: '🔃', name: 'clockwise vertical arrows' },
    { emoji: '🈂️', name: 'Japanese “service charge” button' },
    { emoji: '🈁', name: 'Japanese “here” button' },
    { emoji: '🈹', name: 'Japanese “discount” button' },
    { emoji: '🈶', name: 'Japanese “not free of charge” button' },
    { emoji: '🈯', name: 'japanese “reserved” button', used: 0 },
    { emoji: '🉐', name: 'japanese “bargain” button', used: 0 },

    // Buildings and Places
    { emoji: '🏠', name: 'house' },
    { emoji: '🏡', name: 'house with garden' },
    { emoji: '🏢', name: 'office building' },
    { emoji: '🏬', name: 'department store' },
    { emoji: '🏦', name: 'bank' },
    { emoji: '🏨', name: 'hotel' },
    { emoji: '🏪', name: 'convenience store' },
    { emoji: '🏫', name: 'school' },
    { emoji: '🏥', name: 'hospital' },
    { emoji: '⛪', name: 'church' },
    { emoji: '🕍', name: 'synagogue' },
    { emoji: '🛕', name: 'hindu temple' },

    // Music and Arts
    { emoji: '🎹', name: 'piano' },
    { emoji: '🎻', name: 'violin' },
    { emoji: '🎺', name: 'trumpet' },
    { emoji: '🎷', name: 'saxophone' },
    { emoji: '🎸', name: 'guitar' },
    { emoji: '🎤', name: 'microphone' },
    { emoji: '🎧', name: 'headphone' },
    { emoji: '🎨', name: 'artist palette' },
    { emoji: '🖍️', name: 'crayon' },
    { emoji: '🖌️', name: 'paintbrush' },

    // Technology and Science
    { emoji: '🖥️', name: 'desktop computer' },
    { emoji: '🖨️', name: 'printer' },
    { emoji: '💾', name: 'floppy disk' },
    { emoji: '📼', name: 'videocassette' },
    { emoji: '📹', name: 'video camera' },
    { emoji: '🔬', name: 'microscope' },
    { emoji: '🔭', name: 'telescope' },
    { emoji: '🧪', name: 'test tube' },
    { emoji: '🧫', name: 'petri dish' },
    { emoji: '🧬', name: 'dna' },

    // Zodiac and Astrology
    { emoji: '♈', name: 'aries' },
    { emoji: '♉', name: 'taurus' },
    { emoji: '♊', name: 'gemini' },
    { emoji: '♋', name: 'cancer' },
    { emoji: '♌', name: 'leo' },
    { emoji: '♍', name: 'virgo' },
    { emoji: '♎', name: 'libra' },
    { emoji: '♏', name: 'scorpio' },
    { emoji: '♐', name: 'sagittarius' },
    { emoji: '♑', name: 'capricorn' },
    { emoji: '♒', name: 'aquarius' },
    { emoji: '♓', name: 'pisces' },
];

/**
 * Search our unicode emoji index via human readable name
 * @param {string} search - Emoji Name
 */
function searchEmojis(search) {
    search = search.toLowerCase();
    return arrEmojis.filter(a => a.name.includes(search));
}

/** Return our most used emojis */
function getMostUsedEmojis() {
    return arrEmojis.sort((a, b) => b.used - a.used);
}

/**
 * Checks if the given string consists only of emojis, ignoring whitespace.
 * 
 * @param {string} str - The string to check for emojis.
 * @returns {boolean} True if the string contains only emojis (ignoring whitespace), false otherwise.
 */
function isEmojiOnly(str) {
    // Regular expression to match any emoji character using Unicode property escapes, ignoring whitespace
    const emojiRegex = /^[\s\p{Emoji}]+$/u;
    
    // Test if the string matches the emoji-only pattern
    return emojiRegex.test(str);
}