// Kaomoji for the picker: [face, name, search tags] by category.
// Faces use the full-width forms (＿ ＊ ～ ＼ ｀) where ASCII would read as markdown,
// so they show as typed in Vector and stay plain text everywhere else; the shrug is
// the one exception, rendered as a face by markdown.js. scripts/test-text-color.mjs
// checks every face.
export const KAOMOJI = [
    { name: 'Joy', items: [
        ['(＾▽＾)', 'Beaming', 'happy smile joy grin'],
        ['(◕‿◕)', 'Sweet smile', 'happy smile cute content'],
        ['(｡◕‿◕｡)', 'Bright eyes', 'happy smile cute'],
        ['(✿◠‿◠)', 'Flower smile', 'happy smile cute flower'],
        ['(＾◡＾)', 'Grin', 'happy smile grin'],
        ['(≧▽≦)', 'Overjoyed', 'happy excited joy squee'],
        ['(★▽★)', 'Starry eyes', 'happy excited amazed stars'],
        ['ヽ(・∀・)ﾉ', 'Hooray', 'happy cheer celebrate yay'],
        ['ヽ(＾o＾)ノ', 'Arms up', 'happy cheer yay celebrate'],
        ['＼(＾▽＾)／', 'Banzai', 'happy cheer celebrate yay arms'],
        ['٩(◕‿◕｡)۶', 'Delighted', 'happy cheer excited'],
        ['٩(＾ᴗ＾)۶', 'Pumped', 'happy cheer excited'],
        ['(ﾉ◕ヮ◕)ﾉ', 'Jazz hands', 'happy excited sparkle magic'],
        ['(ﾉ´ヮ｀)ﾉ', 'Throwing joy', 'happy excited celebrate'],
        ['☆ﾐ(o＊･ω･)ﾉ', 'Zoom', 'happy run excited star'],
        ['(´▽｀)', 'Content', 'happy relaxed smile'],
        ['(￣▽￣)', 'Smug grin', 'happy smug grin pleased'],
        ['(＾ｖ＾)', 'Chirpy', 'happy smile'],
        ['(o＾▽＾o)', 'Rosy', 'happy smile cute blush'],
        ['(⌒▽⌒)', 'Cheerful', 'happy smile eyes closed'],
        ['(´∀｀)', 'Glad', 'happy smile'],
        ['o(≧▽≦)o', 'Thrilled', 'happy excited squee'],
        ['(☆ω☆)', 'Dazzled', 'happy amazed stars sparkle'],
        ['(๑˃ᴗ˂)ﻭ', 'Fist pump', 'happy win yes excited'],
        ['(o´▽｀o)', 'Pleased', 'happy smile cute'],
        ['ʘ‿ʘ', 'Wide eyed', 'happy stare smile'],
        ['(•‿•)', 'Simple smile', 'happy smile'],
        ['(ᵔᴥᵔ)', 'Bear smile', 'happy smile cute bear'],
        ['(✯◡✯)', 'Star struck', 'happy amazed stars'],
        ['(｡♡‿♡｡)', 'Smitten', 'happy love heart eyes'],
    ]},
    { name: 'Love', items: [
        ['(♡˙︶˙♡)', 'Lovestruck', 'love heart crush'],
        ['(´｡• ᵕ •｡｀) ♡', 'Soft love', 'love heart cute'],
        ['(◍•ᴗ•◍)❤', 'Holding a heart', 'love heart gift'],
        ['(づ￣ ³￣)づ', 'Kiss me', 'love kiss hug'],
        ['(っ˘з(˘⌣˘ )', 'Smooch', 'love kiss couple'],
        ['(˘³˘)♡', 'Air kiss', 'love kiss heart'],
        ['♡(˃͈ દ ˂͈ ༶ )', 'Adoring', 'love heart cute'],
        ['(人´∀｀)♡', 'Wishful', 'love heart hope'],
        ['(＊˘︶˘＊).｡.:＊♡', 'Dreamy', 'love heart dream'],
        ['(´ε｀ )♡', 'Blowing a kiss', 'love kiss heart'],
        ['ლ(╹◡╹ლ)', 'Reaching for you', 'love want hug'],
        ['(灬♥ω♥灬)', 'Heart eyes', 'love heart eyes blush'],
        ['(◕‿◕)♡', 'With love', 'love heart smile'],
        ['♡＼(￣▽￣)／♡', 'Hearts everywhere', 'love heart cheer'],
        ['(ღ˘⌣˘ღ)', 'Tender', 'love heart calm'],
        ['(｡・//ε//・｡)', 'Shy kiss', 'love kiss blush shy'],
        ['(´,,•ω•,,)♡', 'Bashful love', 'love heart blush shy'],
        ['(ʃƪ˘ﻬ˘)', 'Swooning', 'love dreamy swoon'],
    ]},
    { name: 'Embarrassed', items: [
        ['(⁄ ⁄•⁄ω⁄•⁄ ⁄)', 'Flustered', 'embarrassed blush shy'],
        ['(//▽//)', 'Blushing', 'embarrassed blush shy'],
        ['(〃▽〃)', 'Red cheeks', 'embarrassed blush happy'],
        ['(＾◡＾;)', 'Nervous laugh', 'embarrassed nervous sweat awkward'],
        ['(￣▽￣;)', 'Awkward', 'embarrassed awkward sweat'],
        ['(⌒＿⌒;)', 'Sheepish', 'embarrassed awkward sweat sorry'],
        ['(o^▽^o;)', 'Oops', 'embarrassed oops sweat'],
        ['(＊ﾉωﾉ)', 'Hiding face', 'embarrassed shy hide'],
        ['(ノ＿＜。)', 'Too shy', 'embarrassed shy hide'],
        ['(⁄ ⁄>⁄ ▽ ⁄<⁄ ⁄)', 'Mortified', 'embarrassed blush shy'],
        ['(´,,•ω•,,)', 'Bashful', 'embarrassed blush shy cute'],
        ['(〃＞＿＜;〃)', 'Cringing', 'embarrassed cringe sweat'],
    ]},
    { name: 'Sympathy', items: [
        ['(ノ＿<。)ヾ(´ ▽ ｀ )', 'There there', 'sympathy comfort pat'],
        ['ヽ(￣ω￣(。。 )ゝ', 'Head pat', 'sympathy comfort pat'],
        ['(っ´ω｀)ﾉ(╥ω╥)', 'Consoling', 'sympathy comfort sad cry'],
        ['(ｏ・＿・)ノ”(ᴗ＿ ᴗ。)', 'Pat pat', 'sympathy comfort pat'],
        ['(づ｡◕‿‿◕｡)づ', 'Gentle hug', 'sympathy hug comfort'],
        ['(´；ω；｀)ヾ(･∀･ )', 'It’s okay', 'sympathy comfort cry'],
    ]},
    { name: 'Sadness', items: [
        ['(╥﹏╥)', 'Crying', 'sad cry tears'],
        ['(ಥ﹏ಥ)', 'Sobbing', 'sad cry tears'],
        ['(T▽T)', 'Laugh-crying', 'sad cry laugh tears'],
        ['(；︵；)', 'Teary', 'sad cry tears'],
        ['(｡•́︿•̀｡)', 'Pouting sad', 'sad pout upset'],
        ['(´；ω；｀)', 'Weeping', 'sad cry tears'],
        ['(っ˘̩╭╮˘̩)っ', 'Heartbroken', 'sad cry hurt'],
        ['(ᗒᗣᗕ)՞', 'Wailing', 'sad cry loud'],
        ['(ノД｀)', 'Devastated', 'sad cry despair'],
        ['(｡╯︵╰｡)', 'Gloomy', 'sad down upset'],
        ['(´-ω-｀)', 'Sigh', 'sad tired sigh disappointed'],
        ['(◞‸◟；)', 'Dejected', 'sad down disappointed'],
        ['(｡ŏ﹏ŏ)', 'Whimper', 'sad scared small'],
        ['(つ﹏⊂)', 'Rubbing tears', 'sad cry tears'],
        ['(｡T ω T｡)', 'Sniffle', 'sad cry cute'],
        ['o(TヘTo)', 'Bawling', 'sad cry tears'],
        ['(இ﹏இ｀｡)', 'Hurt', 'sad cry tears'],
        ['(╯︵╰,)', 'Let down', 'sad disappointed'],
    ]},
    { name: 'Anger', items: [
        ['(╬ Ò﹏Ó)', 'Furious', 'angry mad rage'],
        ['(＃｀Д´)', 'Seething', 'angry mad shout'],
        ['(ノಠ益ಠ)ノ', 'Raging', 'angry mad rage'],
        ['ಠ益ಠ', 'Grr', 'angry mad'],
        ['(｀ε´)', 'Pouting', 'angry pout annoyed'],
        ['(￣^￣)', 'Hmph', 'angry pout annoyed'],
        ['(눈＿눈)', 'Glaring', 'angry stare annoyed'],
        ['(•̀ᴗ•́)و', 'Determined', 'angry determined fight'],
        ['ヽ(｀⌒´メ)ノ', 'Tantrum', 'angry mad rage'],
        ['(凸ಠ益ಠ)凸', 'Rude', 'angry mad finger'],
        ['(ﾒ｀ﾛ´)', 'Shouting', 'angry yell shout'],
        ['(▼皿▼＃)', 'Fuming', 'angry mad rage'],
        ['(；￣Д￣)', 'Exasperated', 'angry annoyed tired'],
        ['(ꐦ°᷄д°᷅)', 'Livid', 'angry mad'],
        ['(｀へ´)', 'Grumpy', 'angry grumpy annoyed'],
        ['(¬､¬)', 'Side-eye', 'angry annoyed suspicious'],
    ]},
    { name: 'Fear', items: [
        ['(ﾉﾟ0ﾟ)ﾉ～', 'Running scared', 'fear scared panic run'],
        ['(((;ꏿ﹏ꏿ;)))', 'Trembling', 'fear scared shaking'],
        ['(〇o〇；)', 'Horrified', 'fear shock scared'],
        ['(ノωヽ)', 'Can’t look', 'fear hide scared'],
        ['(／。＼)', 'Covering eyes', 'fear hide scared'],
        ['(ﾟДﾟ;)', 'Panicking', 'fear panic shock'],
        ['〜(＞＜)〜', 'Flailing', 'fear panic'],
        ['(゜ロ゜)', 'Aghast', 'fear shock scared'],
        ['(；；；ﾟДﾟ)', 'Sweating bullets', 'fear nervous panic sweat'],
    ]},
    { name: 'Surprise', items: [
        ['(⊙＿⊙)', 'Stunned', 'surprise shock stare'],
        ['(°o°)', 'Oh', 'surprise shock wow'],
        ['(O＿O)', 'Wide awake', 'surprise shock stare'],
        ['Σ(°△°｜｜｜)', 'Shocked', 'surprise shock'],
        ['(ﾟoﾟ)', 'Gasp', 'surprise gasp wow'],
        ['w(°ｏ°)w', 'Whoa', 'surprise wow amazed'],
        ['(◎＿◎;)', 'Dizzy shock', 'surprise shock dizzy'],
        ['Σ(ノ°▽°)ノ', 'Whoa there', 'surprise excited shock'],
        ['(°ロ°)', 'Jaw drop', 'surprise shock'],
        ['∑(O＿O；)', 'What', 'surprise shock'],
        ['(゜゜)', 'Blank stare', 'surprise stare shock'],
        ['(ﾉﾟ▽ﾟ)ﾉ', 'Amazed', 'surprise excited amazed'],
    ]},
    { name: 'Indifference', items: [
        ['¯\\_(ツ)_/¯', 'Shrug', 'shrug whatever idk'],
        ['┐(￣ヘ￣)┌', 'Whatever', 'shrug whatever meh'],
        ['╮(￣▽￣)╭', 'Oh well', 'shrug whatever'],
        ['ヽ(ー＿ー)ノ', 'Meh', 'shrug whatever meh'],
        ['┐(︶▽︶)┌', 'Don’t care', 'shrug whatever'],
        ['┐(´д｀)┌', 'Ugh, fine', 'shrug annoyed whatever'],
        ['(￣～￣;)', 'Hmm', 'indifferent unsure meh'],
        ['(￣ー￣)', 'Unbothered', 'indifferent smug calm'],
        ['(－＿－)', 'Unamused', 'indifferent bored annoyed'],
        ['(￢＿￢)', 'Deadpan', 'indifferent bored annoyed'],
        ['(ー＿ー)', 'Flat', 'indifferent bored'],
        ['(・＿・)', 'Blank', 'indifferent blank stare'],
        ['ಠ＿ಠ', 'Look of disapproval', 'disapproval stare judge'],
        ['(눈‸눈)', 'Not impressed', 'indifferent annoyed'],
        ['(￣д￣)', 'Bored', 'indifferent bored'],
    ]},
    { name: 'Confusion', items: [
        ['(・・ ) ?', 'Huh', 'confused question'],
        ['(⊙＿◎)', 'Bewildered', 'confused dizzy'],
        ['(￣ω￣;)', 'Puzzled', 'confused sweat'],
        ['(＠＿＠)', 'Dizzy', 'confused dizzy spin'],
        ['(°ヘ°)', 'Doubtful', 'confused doubt'],
        ['(・∧‐)ゞ', 'Scratching head', 'confused think'],
        ['(｀・ω・´)?', 'Wait what', 'confused question'],
        ['(•ิ＿•ิ)?', 'Lost', 'confused question'],
        ['¿ⓧ＿ⓧﮌ', 'Totally lost', 'confused dizzy'],
        ['(｡･ω･｡)?', 'Curious', 'confused curious question cute'],
        ['ლ(ಠ＿ಠ ლ)', 'Why', 'confused annoyed why'],
        ['(￢‿￢ )', 'Suspicious', 'doubt suspicious smirk'],
        ['(¬‿¬)', 'Sly', 'doubt suspicious smirk'],
    ]},
    { name: 'Greeting', items: [
        ['(｡･∀･)ﾉﾞ', 'Hiya', 'greeting hello hi wave'],
        ['(＾ｰ＾)ノ', 'Hello', 'greeting hello hi wave'],
        ['ヾ(＾∇＾)', 'Hey there', 'greeting hello wave'],
        ['(・ω・)ノ', 'Yo', 'greeting hello hi wave'],
        ['ヾ(・ω・＊)', 'Bye bye', 'greeting bye wave'],
        ['(￣▽￣)ノ', 'See ya', 'greeting bye wave'],
        ['(o´ω｀o)ﾉ', 'Good night', 'greeting night bye'],
        ['(ノ゜▽゜)ノ', 'Welcome', 'greeting welcome cheer'],
        ['(｡•̀ᴗ-)✧', 'Wink hello', 'greeting wink'],
        ['＼(⌒▽⌒)', 'Over here', 'greeting wave call'],
        ['(｡・∀・)ノ', 'Good morning', 'greeting morning hello'],
        ['ヾ(￣▽￣) Bye～', 'Later', 'greeting bye wave'],
    ]},
    { name: 'Hugging', items: [
        ['(づ￣ ³￣)づ', 'Hug me', 'hug love'],
        ['(つ≧▽≦)つ', 'Big hug', 'hug happy'],
        ['(っಠ‿ಠ)っ', 'Creepy hug', 'hug creepy'],
        ['(つ✧ω✧)つ', 'Sparkly hug', 'hug sparkle'],
        ['⊂(◉‿◉)つ', 'Gimme hug', 'hug happy'],
        ['⊂(´・ω・｀⊂)', 'Lazy hug', 'hug lazy'],
        ['(っ´▽｀)っ', 'Warm hug', 'hug warm'],
        ['(づ｡◕‿‿◕｡)づ', 'Cuddle', 'hug cuddle cute'],
        ['(ノ＾ヮ＾)ノ', 'Incoming hug', 'hug happy'],
        ['(⊃｡•́‿•̀｡)⊃', 'Hug for you', 'hug cute'],
    ]},
    { name: 'Winking', items: [
        ['(＾＿－)', 'Wink', 'wink'],
        ['(^～^)', 'Teasing wink', 'wink tease'],
        ['(ゝ∀･)', 'Cheeky', 'wink cheeky'],
        ['(｡•̀ᴗ-)✧', 'Sparkle wink', 'wink sparkle'],
        ['(￣ω－)ゞ', 'Salute wink', 'wink salute'],
        ['(•‿-)', 'Small wink', 'wink'],
        ['☆⌒(ゝ。∂)', 'Star wink', 'wink star'],
    ]},
    { name: 'Apologizing', items: [
        ['m(＿ ＿)m', 'Deep bow', 'sorry apologize bow'],
        ['(シ＿ ＿)シ', 'Bowing', 'sorry apologize bow'],
        ['m(＿ ＿;m)', 'Very sorry', 'sorry apologize bow'],
        ['<(＿ ＿)>', 'Humble bow', 'sorry apologize bow thanks'],
        ['(ノ＿ヽ)', 'My bad', 'sorry apologize hide'],
        ['(人＞＜)', 'Please forgive', 'sorry please beg'],
        ['(´･ω･｀)', 'Sorry', 'sorry sad'],
        ['(ᴗ＿ ᴗ。)', 'Regretful', 'sorry sad'],
    ]},
    { name: 'Thinking', items: [
        ['(￣ヘ￣)', 'Pondering', 'think hmm'],
        ['(・ω・)?', 'Wondering', 'think question'],
        ['(｡-‿-｡)', 'Contemplating', 'think calm'],
        ['(ーー;)', 'Concerned', 'think worried'],
        ['(・へ・)', 'Hmm', 'think hmm unsure'],
        ['(￣ー￣)ｂ', 'Thumbs up', 'think good ok approve'],
        ['(•̀ᴗ•́)و ̑̑', 'Got it', 'think ok determined'],
        ['(｀・ω・´)ゞ', 'Roger', 'salute ok yes'],
    ]},
    { name: 'Sleeping', items: [
        ['(－ω－) zzZ', 'Sleeping', 'sleep tired zzz'],
        ['(＿ ＿＊) Z z z', 'Out cold', 'sleep tired zzz'],
        ['(｡-ω-)zzz', 'Nap time', 'sleep nap zzz'],
        ['(∪｡∪)｡｡｡zzZ', 'Deep sleep', 'sleep zzz'],
        ['(-.-)Zzz...', 'Snoozing', 'sleep zzz'],
        ['(´〜｀＊) zzz', 'Drowsy', 'sleep yawn tired'],
        ['(ρ＿-)', 'Rubbing eyes', 'sleep tired wake'],
        ['(～o￣3￣)～', 'Yawning', 'sleep yawn tired'],
        ['(￣o￣) . z Z', 'Dozing off', 'sleep tired zzz'],
    ]},
    { name: 'Running', items: [
        ['ε=ε=ε=┌(;￣▽￣)┘', 'Running away', 'run escape fast'],
        ['ε=ε=(ノ≧∇≦)ノ', 'Rushing', 'run excited fast'],
        ['ヽ(￣д￣;)ノ=3=3=3', 'Fleeing', 'run escape scared'],
        ['C= C= C= C= ┌(｀ー´)┘', 'Dashing', 'run fast'],
        ['ᕕ( ᐛ )ᕗ', 'Here I go', 'run happy walk'],
        ['┏(°.°)┛', 'Strutting', 'walk dance'],
        ['ε=┌( ≧▽≦)┘', 'Zooming off', 'run happy fast'],
    ]},
    { name: 'Dancing', items: [
        ['ヾ(＾▽＾ヾ)', 'Groove', 'dance happy'],
        ['♪(┌・。・)┌', 'Shuffle', 'dance music'],
        ['┌(・。・)┘♪', 'Bop', 'dance music'],
        ['└(＾＾)┐', 'Boogie', 'dance happy'],
        ['ヾ(⌐■＿■)ノ♪', 'Cool dance', 'dance cool sunglasses music'],
        ['(～￣▽￣)～', 'Wiggle', 'dance happy wave'],
        ['〜(꒪꒳꒪)〜', 'Noodle dance', 'dance silly'],
        ['ᕕ(⌐■＿■)ᕗ ♪♬', 'Strut with style', 'dance cool sunglasses music'],
        ['♪～(￣ε￣)', 'Whistling', 'music whistle innocent'],
        ['(ﾉ´ з ｀)ノ♪', 'Singing', 'music sing'],
    ]},
    { name: 'Fighting', items: [
        ['(ง •̀＿•́)ง', 'Fight me', 'fight punch ready'],
        ["(ง'̀-'́)ง", 'Put ’em up', 'fight punch ready'],
        ['(•̀o•́)ง', 'Ready', 'fight determined'],
        ['(ﾉ｀Д´)ﾉ', 'Charge', 'fight angry attack'],
        ['(｀･ω･´)ゞ', 'Reporting for duty', 'salute ready'],
        ['（ ・∀・）・・・--------☆', 'Pew pew', 'shoot attack magic'],
        ['(ﾒ ﾟ皿ﾟ)ﾒ', 'Brawler', 'fight angry'],
        ['(∩ᄑ＿ᄑ)⊃━☆ﾟ＊･｡＊･:≡( ε:)', 'Spell attack', 'magic attack wizard'],
        ['ᕦ(ò＿óˇ)ᕤ', 'Flexing', 'strong muscle flex'],
        ['ᕙ(⇀‸↼‶)ᕗ', 'Strong', 'strong muscle flex'],
    ]},
    { name: 'Magic', items: [
        ['(ﾉ>ω<)ﾉ :｡･:＊:･ﾟ’★,｡･:＊:･ﾟ’☆', 'Casting sparkles', 'magic sparkle stars'],
        ['(∩｀-´)⊃━☆ﾟ.＊･｡ﾟ', 'Magic wand', 'magic wand spell'],
        ['(ノ°∀°)ノ⌒･＊:.｡. .｡.:＊･゜ﾟ･＊☆', 'Glitter toss', 'magic sparkle'],
        ['(☆▽☆)', 'Sparkly eyes', 'magic sparkle stars'],
        ['(ﾉ◕ヮ◕)ﾉ:･ﾟ✧', 'Sprinkling magic', 'magic sparkle happy'],
        ['✧･ﾟ: ✧･ﾟ:(◕‿◕):･ﾟ✧:･ﾟ✧', 'Surrounded by sparkles', 'magic sparkle happy'],
    ]},
    { name: 'Table', items: [
        ['(╯°□°)╯︵ ┻━┻', 'Table flip', 'table flip angry rage'],
        ['(ノಠ益ಠ)ノ彡┻━┻', 'Rage flip', 'table flip angry rage'],
        ['┻━┻ ︵ヽ(｀Д´)ﾉ︵ ┻━┻', 'Double flip', 'table flip angry'],
        ['┬─┬ノ( º ＿ ºノ)', 'Put it back', 'table unflip calm'],
        ['(ヘ･＿･)ヘ┳━┳', 'Setting the table', 'table unflip'],
        ['┻━┻ミ＼(≧ﾛ≦＼)', 'Table smash', 'table flip angry'],
        ['(ノ°▽°)ノ︵┻━┻', 'Happy flip', 'table flip happy'],
    ]},
    { name: 'Cats', items: [
        ['(=^･ω･^=)', 'Kitty', 'cat kitty meow'],
        ['(=^‥^=)', 'Cat face', 'cat kitty meow'],
        ['(^・ω・^ )', 'Curious cat', 'cat kitty'],
        ['ฅ^•ﻌ•^ฅ', 'Cat paws', 'cat kitty paws meow'],
        ['(=ↀωↀ=)', 'Wide-eyed cat', 'cat kitty'],
        ['(＾・ω・＾✿)', 'Flower cat', 'cat kitty cute'],
        ['ᓚᘏᗢ', 'Loafing cat', 'cat kitty loaf'],
        ['(=｀ω´=)', 'Grumpy cat', 'cat kitty angry'],
        ['(=;ェ;=)', 'Sad cat', 'cat kitty sad'],
        ['(^˵◕ω◕˵^)', 'Happy cat', 'cat kitty happy'],
        ['ↀ‿ↀ', 'Cat stare', 'cat stare'],
        ['(=①ω①=)', 'Big eyed cat', 'cat kitty'],
        ['ヾ(=｀ω´=)ノ”', 'Hissing cat', 'cat angry hiss'],
        ['(ᵔᴥᵔ)', 'Smiling cat', 'cat bear happy'],
    ]},
    { name: 'Bears', items: [
        ['ʕ•ᴥ•ʔ', 'Bear', 'bear cute'],
        ['ʕ ᵔᴥᵔ ʔ', 'Happy bear', 'bear happy'],
        ['ʕ•̀ω•́ʔ✧', 'Determined bear', 'bear determined'],
        ['ʕ´•ᴥ•｀ʔ', 'Sad bear', 'bear sad'],
        ['ʕノ•ᴥ•ʔノ ︵ ┻━┻', 'Bear table flip', 'bear table flip'],
        ['ʕ￫ᴥ￩ʔ', 'Squinting bear', 'bear'],
        ['ʕっ•ᴥ•ʔっ', 'Bear hug', 'bear hug'],
        ['ʕ ˵• ₒ •˵ ʔ', 'Surprised bear', 'bear surprise'],
        ['(´(ｪ)｀)', 'Teddy', 'bear teddy'],
        ['ʕ•ᴥ•ʔﾉ♡', 'Bear love', 'bear love heart'],
    ]},
    { name: 'Dogs', items: [
        ['∪＾ェ＾∪', 'Puppy', 'dog puppy'],
        ['∪･ω･∪', 'Doggo', 'dog puppy'],
        ['V●ᴥ●V', 'Good boy', 'dog puppy'],
        ['(▽◕ ᴥ ◕▽)', 'Fluffy dog', 'dog puppy'],
        ['໒( ●ᴥ ●)ʋ', 'Pup', 'dog puppy'],
        ['(❍ᴥ❍ʋ)', 'Waggy', 'dog puppy happy'],
        ['∪￣-￣∪', 'Sleepy dog', 'dog sleep'],
    ]},
    { name: 'Animals', items: [
        ['／(･ × ･)＼', 'Bunny', 'rabbit bunny'],
        ['(＼(•ᴗ•)/)', 'Rabbit ears', 'rabbit bunny'],
        ['(＾ºﾛº＾)', 'Hamster', 'hamster mouse'],
        ['(´・ω・)つ旦', 'Tea time', 'tea drink'],
        ['ʚ(•ϖ•)ɞ', 'Butterfly', 'butterfly bug'],
        ['(•ө•)♡', 'Chick', 'bird chick love'],
        ['(・θ・)', 'Little bird', 'bird'],
        ['(゜)>', 'Penguin', 'bird penguin'],
        ['<コ:彡', 'Squid', 'squid sea'],
        ['<゜)))彡', 'Fish', 'fish sea'],
        ['/╲/＼╭(ఠఠ益ఠఠ)╮/＼╱＼', 'Spider', 'spider bug scary'],
        ['(^(ｴ)^)', 'Panda', 'panda bear'],
        ['( ´(00)ˋ )', 'Piggy', 'pig'],
        ['(•(OO)•)', 'Pig snout', 'pig'],
        ['🐾(=･ω･=)', 'Paw prints', 'cat paw'],
        ['ˁ˚ᴥ˚ˀ', 'Little critter', 'animal cute'],
    ]},
    { name: 'Food', items: [
        ['(っ˘ڡ˘ς)', 'Yummy', 'food eat yum delicious'],
        ['( ˘▽˘)っ♨', 'Hot food', 'food hot eat'],
        ['(o˘◡˘o) ┌iii┐', 'Birthday cake', 'food cake birthday'],
        ['(っ・ω・)っ🍪', 'Cookie for you', 'food cookie give'],
        ['(￣～￣)', 'Chewing', 'food eat chew'],
        ['(＊￣з￣)', 'Slurp', 'food drink slurp'],
        ['(o´ڡ｀o)', 'Delicious', 'food yum delicious'],
        ['( ˘ ³˘)ノ°ﾟº❍｡', 'Bubble tea', 'food drink bubbles'],
        ['(っ˘ω˘ς )', 'Snacking', 'food eat snack'],
        ['(｀・ω・)ノ🍺', 'Cheers', 'drink beer cheers toast'],
        ['(＊^▽^)/★＊☆♪', 'Party', 'party celebrate music'],
    ]},
    { name: 'Lenny', items: [
        ['( ͡° ͜ʖ ͡°)', 'Lenny', 'lenny smirk'],
        ['( ͡～ ͜ʖ ͡°)', 'Lenny wink', 'lenny wink'],
        ['( ͠° ͟ʖ ͡°)', 'Lenny sus', 'lenny suspicious'],
        ['( ͡ᵔ ͜ʖ ͡ᵔ )', 'Happy Lenny', 'lenny happy'],
        ['( ͡°( ͡° ͜ʖ( ͡° ͜ʖ ͡°)ʖ ͡°) ͡°)', 'Lenny crowd', 'lenny crowd many'],
        ['(☞ ͡° ͜ʖ ͡°)☞', 'Lenny points', 'lenny point you'],
        ['( ͡ʘ ͜ʖ ͡ʘ)', 'Lenny stare', 'lenny stare'],
        ['¯＼＿( ͡° ͜ʖ ͡°)＿/¯', 'Lenny shrug', 'lenny shrug'],
    ]},
    { name: 'Cool', items: [
        ['(⌐■＿■)', 'Deal with it', 'cool sunglasses'],
        ['( •＿•)>⌐■-■', 'Putting on shades', 'cool sunglasses'],
        ['(▀̿Ĺ̯▀̿ ̿)', 'Too cool', 'cool sunglasses'],
        ['(☞ﾟヮﾟ)☞', 'Finger guns', 'cool point you'],
        ['☜(ﾟヮﾟ☜)', 'Pointing back', 'cool point'],
        ['(•̀ᴗ•́)و', 'Nailed it', 'cool win yes'],
        ['ᕦ(ò＿óˇ)ᕤ', 'Flex', 'cool strong muscle'],
        ['(✌ﾟ∀ﾟ)☞', 'Peace and point', 'cool peace'],
        ['d(￣▽￣)b', 'Two thumbs up', 'cool good approve thumbs'],
        ['(b ᵔ▽ᵔ)b', 'Approved', 'cool good approve thumbs'],
    ]},
    { name: 'Misc', items: [
        ['(°ロ°)☝', 'Eureka', 'idea point aha'],
        ['φ(..)', 'Taking notes', 'write notes'],
        ['＿φ(°-°=)', 'Studying', 'write study'],
        ['(・ε・)', 'Whistle', 'innocent whistle'],
        ['ヽ(°〇°)ﾉ', 'Help', 'help panic'],
        ['(＃＞＜)', 'Frustrated', 'frustrated annoyed'],
        ['(✖╭╮✖)', 'Dead', 'dead ko'],
        ['(×﹏×)', 'Knocked out', 'dead ko dizzy'],
        ['(ᗒᗨᗕ)', 'Screaming', 'scream excited loud'],
        ['(✧ω✧)', 'Glittering', 'sparkle excited'],
        ['(⊃｡•́‿•̀｡)⊃━✿✿✿', 'Flowers for you', 'flowers give gift'],
        ['(っ＾▿＾)💨', 'Off I go', 'leave fast'],
        ['(o・ω・o)', 'Round face', 'cute curious'],
        ['(｡◕‿‿◕｡)', 'Big grin', 'happy smile'],
        ['┬┴┬┴┤(･＿├┬┴┬┴', 'Peeking', 'hide peek wall'],
        ['｜ʘ‿ʘ)╯', 'Peek-a-boo', 'hide peek'],
    ]},
];
